language: go
go:
  - 1.13.x
sudo: false
cache:
  directories:
    - $GOCACHE
    - $GOPATH/pkg/mod
env:
  global:
    - GOCACHE=$HOME/.go-build
  matrix:
    - RACE=true
    - ITEST=true
    - REMOTEWALLET_ITEST=true
    - REMOTEWALLET_RACE=true
#    - COVER=true

install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0
script:
  - export GO111MODULE=on
  - go build
  - golangci-lint --version
  - golangci-lint run --build-tags "autopilotrpc chainrpc invoicesrpc routerrpc signrpc walletrpc watchtowerrpc wtclientrpc" --disable-all --deadline=10m
      --skip-files="mobile\\/.*generated\\.go"
      --enable=gofmt
      --enable=vet
      --enable=gosimple
      --enable=unconvert
      --enable=ineffassign
      --enable=unused

  # Run unit tests with race condition detector.
  - 'if [ "$RACE" = true ]; then make travis-race ; fi'

  # Run unit tests with race condition detector for the remote wallet impl.
  - 'if [ "$REMOTEWALLET_RACE" = true ]; then make travis-race walletimpl=remotewallet; fi'

  # Run integration tests.
  - 'if [ "$ITEST" = true ]; then make travis-itest; fi'

  # Run remote wallet integration tests.
  - 'if [ "$REMOTEWALLET_ITEST" = true ]; then make travis-itest walletimpl=remotewallet; fi'

  # Run unit tests and generate coverage report.
  - 'if [ "$COVER" = true ]; then make travis-cover; fi'

after_script:
  - LOG_FILES=./lntest/itest/*.log
  - echo "Uploading to termbin.com..."
  - find $LOG_FILES | xargs -I{} sh -c "cat {} | nc termbin.com 9999 | xargs -r0 printf '{} uploaded to %s'"
  - echo "Uploading to file.io..."
  - tar -zcvO $LOG_FILES | curl -s -F 'file=@-;filename=logs.tar.gz' https://file.io | xargs -r0 printf 'logs.tar.gz uploaded to %s\n'
