// Code generated by protoc-gen-go. DO NOT EDIT.
// source: walletrpc/walletkit.proto

package walletrpc // import "github.com/decred/dcrlnd/lnrpc/walletrpc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import lnrpc "github.com/decred/dcrlnd/lnrpc"
import signrpc "github.com/decred/dcrlnd/lnrpc/signrpc"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WitnessType int32

const (
	WitnessType_UNKNOWN_WITNESS WitnessType = 0
	//
	// A witness that allows us to spend the output of a commitment transaction
	// after a relative lock-time lockout.
	WitnessType_COMMITMENT_TIME_LOCK WitnessType = 1
	//
	// A witness that allows us to spend a settled no-delay output immediately on a
	// counterparty's commitment transaction.
	WitnessType_COMMITMENT_NO_DELAY WitnessType = 2
	//
	// A witness that allows us to sweep the settled output of a malicious
	// counterparty's who broadcasts a revoked commitment transaction.
	WitnessType_COMMITMENT_REVOKE WitnessType = 3
	//
	// A witness that allows us to sweep an HTLC which we offered to the remote
	// party in the case that they broadcast a revoked commitment state.
	WitnessType_HTLC_OFFERED_REVOKE WitnessType = 4
	//
	// A witness that allows us to sweep an HTLC output sent to us in the case that
	// the remote party broadcasts a revoked commitment state.
	WitnessType_HTLC_ACCEPTED_REVOKE WitnessType = 5
	//
	// A witness that allows us to sweep an HTLC output that we extended to a
	// party, but was never fulfilled.  This HTLC output isn't directly on the
	// commitment transaction, but is the result of a confirmed second-level HTLC
	// transaction. As a result, we can only spend this after a CSV delay.
	WitnessType_HTLC_OFFERED_TIMEOUT_SECOND_LEVEL WitnessType = 6
	//
	// A witness that allows us to sweep an HTLC output that was offered to us, and
	// for which we have a payment preimage. This HTLC output isn't directly on our
	// commitment transaction, but is the result of confirmed second-level HTLC
	// transaction. As a result, we can only spend this after a CSV delay.
	WitnessType_HTLC_ACCEPTED_SUCCESS_SECOND_LEVEL WitnessType = 7
	//
	// A witness that allows us to sweep an HTLC that we offered to the remote
	// party which lies in the commitment transaction of the remote party. We can
	// spend this output after the absolute CLTV timeout of the HTLC as passed.
	WitnessType_HTLC_OFFERED_REMOTE_TIMEOUT WitnessType = 8
	//
	// A witness that allows us to sweep an HTLC that was offered to us by the
	// remote party. We use this witness in the case that the remote party goes to
	// chain, and we know the pre-image to the HTLC. We can sweep this without any
	// additional timeout.
	WitnessType_HTLC_ACCEPTED_REMOTE_SUCCESS WitnessType = 9
	//
	// A witness that allows us to sweep an HTLC from the remote party's commitment
	// transaction in the case that the broadcast a revoked commitment, but then
	// also immediately attempt to go to the second level to claim the HTLC.
	WitnessType_HTLC_SECOND_LEVEL_REVOKE WitnessType = 10
	//
	// A witness type that allows us to spend a regular p2wkh output that's sent to
	// an output which is under complete control of the backing wallet.
	WitnessType_WITNESS_KEY_HASH WitnessType = 11
	//
	// A witness type that allows us to sweep an output that sends to a nested P2SH
	// script that pays to a key solely under our control.
	WitnessType_NESTED_WITNESS_KEY_HASH WitnessType = 12
	//
	// A witness type that allows us to sweep an output that sends to a P2PKH
	// script.
	WitnessType_PUBKEY_HASH WitnessType = 128
)

var WitnessType_name = map[int32]string{
	0:   "UNKNOWN_WITNESS",
	1:   "COMMITMENT_TIME_LOCK",
	2:   "COMMITMENT_NO_DELAY",
	3:   "COMMITMENT_REVOKE",
	4:   "HTLC_OFFERED_REVOKE",
	5:   "HTLC_ACCEPTED_REVOKE",
	6:   "HTLC_OFFERED_TIMEOUT_SECOND_LEVEL",
	7:   "HTLC_ACCEPTED_SUCCESS_SECOND_LEVEL",
	8:   "HTLC_OFFERED_REMOTE_TIMEOUT",
	9:   "HTLC_ACCEPTED_REMOTE_SUCCESS",
	10:  "HTLC_SECOND_LEVEL_REVOKE",
	11:  "WITNESS_KEY_HASH",
	12:  "NESTED_WITNESS_KEY_HASH",
	128: "PUBKEY_HASH",
}
var WitnessType_value = map[string]int32{
	"UNKNOWN_WITNESS":                    0,
	"COMMITMENT_TIME_LOCK":               1,
	"COMMITMENT_NO_DELAY":                2,
	"COMMITMENT_REVOKE":                  3,
	"HTLC_OFFERED_REVOKE":                4,
	"HTLC_ACCEPTED_REVOKE":               5,
	"HTLC_OFFERED_TIMEOUT_SECOND_LEVEL":  6,
	"HTLC_ACCEPTED_SUCCESS_SECOND_LEVEL": 7,
	"HTLC_OFFERED_REMOTE_TIMEOUT":        8,
	"HTLC_ACCEPTED_REMOTE_SUCCESS":       9,
	"HTLC_SECOND_LEVEL_REVOKE":           10,
	"WITNESS_KEY_HASH":                   11,
	"NESTED_WITNESS_KEY_HASH":            12,
	"PUBKEY_HASH":                        128,
}

func (x WitnessType) String() string {
	return proto.EnumName(WitnessType_name, int32(x))
}
func (WitnessType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_walletkit_17ae671db9771517, []int{0}
}

type KeyReq struct {
	// *
	// Is the key finger print of the root pubkey that this request is targeting.
	// This allows the WalletKit to possibly serve out keys for multiple HD chains
	// via public derivation.
	KeyFingerPrint int32 `protobuf:"varint,1,opt,name=key_finger_print,json=keyFingerPrint,proto3" json:"key_finger_print,omitempty"`
	// *
	// The target key family to derive a key from. In other contexts, this is
	// known as the "account".
	KeyFamily            int32    `protobuf:"varint,2,opt,name=key_family,json=keyFamily,proto3" json:"key_family,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyReq) Reset()         { *m = KeyReq{} }
func (m *KeyReq) String() string { return proto.CompactTextString(m) }
func (*KeyReq) ProtoMessage()    {}
func (*KeyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletkit_17ae671db9771517, []int{0}
}
func (m *KeyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyReq.Unmarshal(m, b)
}
func (m *KeyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyReq.Marshal(b, m, deterministic)
}
func (dst *KeyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyReq.Merge(dst, src)
}
func (m *KeyReq) XXX_Size() int {
	return xxx_messageInfo_KeyReq.Size(m)
}
func (m *KeyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyReq.DiscardUnknown(m)
}

var xxx_messageInfo_KeyReq proto.InternalMessageInfo

func (m *KeyReq) GetKeyFingerPrint() int32 {
	if m != nil {
		return m.KeyFingerPrint
	}
	return 0
}

func (m *KeyReq) GetKeyFamily() int32 {
	if m != nil {
		return m.KeyFamily
	}
	return 0
}

type AddrRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddrRequest) Reset()         { *m = AddrRequest{} }
func (m *AddrRequest) String() string { return proto.CompactTextString(m) }
func (*AddrRequest) ProtoMessage()    {}
func (*AddrRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletkit_17ae671db9771517, []int{1}
}
func (m *AddrRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddrRequest.Unmarshal(m, b)
}
func (m *AddrRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddrRequest.Marshal(b, m, deterministic)
}
func (dst *AddrRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddrRequest.Merge(dst, src)
}
func (m *AddrRequest) XXX_Size() int {
	return xxx_messageInfo_AddrRequest.Size(m)
}
func (m *AddrRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddrRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddrRequest proto.InternalMessageInfo

type AddrResponse struct {
	// *
	// The address encoded using a bech32 format.
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddrResponse) Reset()         { *m = AddrResponse{} }
func (m *AddrResponse) String() string { return proto.CompactTextString(m) }
func (*AddrResponse) ProtoMessage()    {}
func (*AddrResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletkit_17ae671db9771517, []int{2}
}
func (m *AddrResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddrResponse.Unmarshal(m, b)
}
func (m *AddrResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddrResponse.Marshal(b, m, deterministic)
}
func (dst *AddrResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddrResponse.Merge(dst, src)
}
func (m *AddrResponse) XXX_Size() int {
	return xxx_messageInfo_AddrResponse.Size(m)
}
func (m *AddrResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddrResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddrResponse proto.InternalMessageInfo

func (m *AddrResponse) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type Transaction struct {
	// *
	// The raw serialized transaction.
	TxHex                []byte   `protobuf:"bytes,1,opt,name=tx_hex,json=txHex,proto3" json:"tx_hex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletkit_17ae671db9771517, []int{3}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTxHex() []byte {
	if m != nil {
		return m.TxHex
	}
	return nil
}

type PublishResponse struct {
	// *
	// If blank, then no error occurred and the transaction was successfully
	// published. If not the empty string, then a string representation of the
	// broadcast error.
	//
	// TODO(roasbeef): map to a proper enum type
	PublishError         string   `protobuf:"bytes,1,opt,name=publish_error,json=publishError,proto3" json:"publish_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishResponse) Reset()         { *m = PublishResponse{} }
func (m *PublishResponse) String() string { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()    {}
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletkit_17ae671db9771517, []int{4}
}
func (m *PublishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResponse.Unmarshal(m, b)
}
func (m *PublishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResponse.Marshal(b, m, deterministic)
}
func (dst *PublishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResponse.Merge(dst, src)
}
func (m *PublishResponse) XXX_Size() int {
	return xxx_messageInfo_PublishResponse.Size(m)
}
func (m *PublishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResponse proto.InternalMessageInfo

func (m *PublishResponse) GetPublishError() string {
	if m != nil {
		return m.PublishError
	}
	return ""
}

type SendOutputsRequest struct {
	// *
	// The number of atoms per kilobyte that should be used when crafting
	// this transaction.
	AtomsPerKb int64 `protobuf:"varint,1,opt,name=atoms_per_kb,json=atomsPerKb,proto3" json:"atoms_per_kb,omitempty"`
	// *
	// A slice of the outputs that should be created in the transaction produced.
	Outputs              []*signrpc.TxOut `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SendOutputsRequest) Reset()         { *m = SendOutputsRequest{} }
func (m *SendOutputsRequest) String() string { return proto.CompactTextString(m) }
func (*SendOutputsRequest) ProtoMessage()    {}
func (*SendOutputsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletkit_17ae671db9771517, []int{5}
}
func (m *SendOutputsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendOutputsRequest.Unmarshal(m, b)
}
func (m *SendOutputsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendOutputsRequest.Marshal(b, m, deterministic)
}
func (dst *SendOutputsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendOutputsRequest.Merge(dst, src)
}
func (m *SendOutputsRequest) XXX_Size() int {
	return xxx_messageInfo_SendOutputsRequest.Size(m)
}
func (m *SendOutputsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendOutputsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendOutputsRequest proto.InternalMessageInfo

func (m *SendOutputsRequest) GetAtomsPerKb() int64 {
	if m != nil {
		return m.AtomsPerKb
	}
	return 0
}

func (m *SendOutputsRequest) GetOutputs() []*signrpc.TxOut {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type SendOutputsResponse struct {
	// *
	// The serialized transaction sent out on the network.
	RawTx                []byte   `protobuf:"bytes,1,opt,name=raw_tx,json=rawTx,proto3" json:"raw_tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendOutputsResponse) Reset()         { *m = SendOutputsResponse{} }
func (m *SendOutputsResponse) String() string { return proto.CompactTextString(m) }
func (*SendOutputsResponse) ProtoMessage()    {}
func (*SendOutputsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletkit_17ae671db9771517, []int{6}
}
func (m *SendOutputsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendOutputsResponse.Unmarshal(m, b)
}
func (m *SendOutputsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendOutputsResponse.Marshal(b, m, deterministic)
}
func (dst *SendOutputsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendOutputsResponse.Merge(dst, src)
}
func (m *SendOutputsResponse) XXX_Size() int {
	return xxx_messageInfo_SendOutputsResponse.Size(m)
}
func (m *SendOutputsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendOutputsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendOutputsResponse proto.InternalMessageInfo

func (m *SendOutputsResponse) GetRawTx() []byte {
	if m != nil {
		return m.RawTx
	}
	return nil
}

type EstimateFeeRequest struct {
	// *
	// The number of confirmations to shoot for when estimating the fee.
	ConfTarget           int32    `protobuf:"varint,1,opt,name=conf_target,json=confTarget,proto3" json:"conf_target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstimateFeeRequest) Reset()         { *m = EstimateFeeRequest{} }
func (m *EstimateFeeRequest) String() string { return proto.CompactTextString(m) }
func (*EstimateFeeRequest) ProtoMessage()    {}
func (*EstimateFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletkit_17ae671db9771517, []int{7}
}
func (m *EstimateFeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstimateFeeRequest.Unmarshal(m, b)
}
func (m *EstimateFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstimateFeeRequest.Marshal(b, m, deterministic)
}
func (dst *EstimateFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstimateFeeRequest.Merge(dst, src)
}
func (m *EstimateFeeRequest) XXX_Size() int {
	return xxx_messageInfo_EstimateFeeRequest.Size(m)
}
func (m *EstimateFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EstimateFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EstimateFeeRequest proto.InternalMessageInfo

func (m *EstimateFeeRequest) GetConfTarget() int32 {
	if m != nil {
		return m.ConfTarget
	}
	return 0
}

type EstimateFeeResponse struct {
	// *
	// The amount of atoms per kilobyte that should be used in order to reach the
	// confirmation target in the request.
	AtomsPerKb           int64    `protobuf:"varint,1,opt,name=atoms_per_kb,json=atomsPerKb,proto3" json:"atoms_per_kb,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstimateFeeResponse) Reset()         { *m = EstimateFeeResponse{} }
func (m *EstimateFeeResponse) String() string { return proto.CompactTextString(m) }
func (*EstimateFeeResponse) ProtoMessage()    {}
func (*EstimateFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletkit_17ae671db9771517, []int{8}
}
func (m *EstimateFeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstimateFeeResponse.Unmarshal(m, b)
}
func (m *EstimateFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstimateFeeResponse.Marshal(b, m, deterministic)
}
func (dst *EstimateFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstimateFeeResponse.Merge(dst, src)
}
func (m *EstimateFeeResponse) XXX_Size() int {
	return xxx_messageInfo_EstimateFeeResponse.Size(m)
}
func (m *EstimateFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EstimateFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EstimateFeeResponse proto.InternalMessageInfo

func (m *EstimateFeeResponse) GetAtomsPerKb() int64 {
	if m != nil {
		return m.AtomsPerKb
	}
	return 0
}

type PendingSweep struct {
	// The outpoint of the output we're attempting to sweep.
	Outpoint *lnrpc.OutPoint `protobuf:"bytes,1,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	// The witness type of the output we're attempting to sweep.
	WitnessType WitnessType `protobuf:"varint,2,opt,name=witness_type,proto3,enum=walletrpc.WitnessType" json:"witness_type,omitempty"`
	// The value of the output we're attempting to sweep.
	AmountAtoms uint32 `protobuf:"varint,3,opt,name=amount_atoms,proto3" json:"amount_atoms,omitempty"`
	//
	// The fee rate we'll use to sweep the output. The fee rate is only determined
	// once a sweeping transaction for the output is created, so it's possible for
	// this to be 0 before this.
	AtomsPerByte uint32 `protobuf:"varint,4,opt,name=atoms_per_byte,proto3" json:"atoms_per_byte,omitempty"`
	// The number of broadcast attempts we've made to sweep the output.
	BroadcastAttempts uint32 `protobuf:"varint,5,opt,name=broadcast_attempts,proto3" json:"broadcast_attempts,omitempty"`
	//
	// The next height of the chain at which we'll attempt to broadcast the
	// sweep transaction of the output.
	NextBroadcastHeight  uint32   `protobuf:"varint,6,opt,name=next_broadcast_height,proto3" json:"next_broadcast_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendingSweep) Reset()         { *m = PendingSweep{} }
func (m *PendingSweep) String() string { return proto.CompactTextString(m) }
func (*PendingSweep) ProtoMessage()    {}
func (*PendingSweep) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletkit_17ae671db9771517, []int{9}
}
func (m *PendingSweep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingSweep.Unmarshal(m, b)
}
func (m *PendingSweep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingSweep.Marshal(b, m, deterministic)
}
func (dst *PendingSweep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingSweep.Merge(dst, src)
}
func (m *PendingSweep) XXX_Size() int {
	return xxx_messageInfo_PendingSweep.Size(m)
}
func (m *PendingSweep) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingSweep.DiscardUnknown(m)
}

var xxx_messageInfo_PendingSweep proto.InternalMessageInfo

func (m *PendingSweep) GetOutpoint() *lnrpc.OutPoint {
	if m != nil {
		return m.Outpoint
	}
	return nil
}

func (m *PendingSweep) GetWitnessType() WitnessType {
	if m != nil {
		return m.WitnessType
	}
	return WitnessType_UNKNOWN_WITNESS
}

func (m *PendingSweep) GetAmountAtoms() uint32 {
	if m != nil {
		return m.AmountAtoms
	}
	return 0
}

func (m *PendingSweep) GetAtomsPerByte() uint32 {
	if m != nil {
		return m.AtomsPerByte
	}
	return 0
}

func (m *PendingSweep) GetBroadcastAttempts() uint32 {
	if m != nil {
		return m.BroadcastAttempts
	}
	return 0
}

func (m *PendingSweep) GetNextBroadcastHeight() uint32 {
	if m != nil {
		return m.NextBroadcastHeight
	}
	return 0
}

type PendingSweepsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendingSweepsRequest) Reset()         { *m = PendingSweepsRequest{} }
func (m *PendingSweepsRequest) String() string { return proto.CompactTextString(m) }
func (*PendingSweepsRequest) ProtoMessage()    {}
func (*PendingSweepsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletkit_17ae671db9771517, []int{10}
}
func (m *PendingSweepsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingSweepsRequest.Unmarshal(m, b)
}
func (m *PendingSweepsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingSweepsRequest.Marshal(b, m, deterministic)
}
func (dst *PendingSweepsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingSweepsRequest.Merge(dst, src)
}
func (m *PendingSweepsRequest) XXX_Size() int {
	return xxx_messageInfo_PendingSweepsRequest.Size(m)
}
func (m *PendingSweepsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingSweepsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PendingSweepsRequest proto.InternalMessageInfo

type PendingSweepsResponse struct {
	//
	// The set of outputs currently being swept by lnd's central batching engine.
	PendingSweeps        []*PendingSweep `protobuf:"bytes,1,rep,name=pending_sweeps,proto3" json:"pending_sweeps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PendingSweepsResponse) Reset()         { *m = PendingSweepsResponse{} }
func (m *PendingSweepsResponse) String() string { return proto.CompactTextString(m) }
func (*PendingSweepsResponse) ProtoMessage()    {}
func (*PendingSweepsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletkit_17ae671db9771517, []int{11}
}
func (m *PendingSweepsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingSweepsResponse.Unmarshal(m, b)
}
func (m *PendingSweepsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingSweepsResponse.Marshal(b, m, deterministic)
}
func (dst *PendingSweepsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingSweepsResponse.Merge(dst, src)
}
func (m *PendingSweepsResponse) XXX_Size() int {
	return xxx_messageInfo_PendingSweepsResponse.Size(m)
}
func (m *PendingSweepsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingSweepsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PendingSweepsResponse proto.InternalMessageInfo

func (m *PendingSweepsResponse) GetPendingSweeps() []*PendingSweep {
	if m != nil {
		return m.PendingSweeps
	}
	return nil
}

type BumpFeeRequest struct {
	// The input we're attempting to bump the fee of.
	Outpoint *lnrpc.OutPoint `protobuf:"bytes,1,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	// The target number of blocks that the input should be spent within.
	TargetConf uint32 `protobuf:"varint,2,opt,name=target_conf,proto3" json:"target_conf,omitempty"`
	//
	// The fee rate, expressed in sat/byte, that should be used to spend the input
	// with.
	AtomsPerByte         uint32   `protobuf:"varint,3,opt,name=atoms_per_byte,proto3" json:"atoms_per_byte,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BumpFeeRequest) Reset()         { *m = BumpFeeRequest{} }
func (m *BumpFeeRequest) String() string { return proto.CompactTextString(m) }
func (*BumpFeeRequest) ProtoMessage()    {}
func (*BumpFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletkit_17ae671db9771517, []int{12}
}
func (m *BumpFeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BumpFeeRequest.Unmarshal(m, b)
}
func (m *BumpFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BumpFeeRequest.Marshal(b, m, deterministic)
}
func (dst *BumpFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BumpFeeRequest.Merge(dst, src)
}
func (m *BumpFeeRequest) XXX_Size() int {
	return xxx_messageInfo_BumpFeeRequest.Size(m)
}
func (m *BumpFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BumpFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BumpFeeRequest proto.InternalMessageInfo

func (m *BumpFeeRequest) GetOutpoint() *lnrpc.OutPoint {
	if m != nil {
		return m.Outpoint
	}
	return nil
}

func (m *BumpFeeRequest) GetTargetConf() uint32 {
	if m != nil {
		return m.TargetConf
	}
	return 0
}

func (m *BumpFeeRequest) GetAtomsPerByte() uint32 {
	if m != nil {
		return m.AtomsPerByte
	}
	return 0
}

type BumpFeeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BumpFeeResponse) Reset()         { *m = BumpFeeResponse{} }
func (m *BumpFeeResponse) String() string { return proto.CompactTextString(m) }
func (*BumpFeeResponse) ProtoMessage()    {}
func (*BumpFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_walletkit_17ae671db9771517, []int{13}
}
func (m *BumpFeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BumpFeeResponse.Unmarshal(m, b)
}
func (m *BumpFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BumpFeeResponse.Marshal(b, m, deterministic)
}
func (dst *BumpFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BumpFeeResponse.Merge(dst, src)
}
func (m *BumpFeeResponse) XXX_Size() int {
	return xxx_messageInfo_BumpFeeResponse.Size(m)
}
func (m *BumpFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BumpFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BumpFeeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*KeyReq)(nil), "walletrpc.KeyReq")
	proto.RegisterType((*AddrRequest)(nil), "walletrpc.AddrRequest")
	proto.RegisterType((*AddrResponse)(nil), "walletrpc.AddrResponse")
	proto.RegisterType((*Transaction)(nil), "walletrpc.Transaction")
	proto.RegisterType((*PublishResponse)(nil), "walletrpc.PublishResponse")
	proto.RegisterType((*SendOutputsRequest)(nil), "walletrpc.SendOutputsRequest")
	proto.RegisterType((*SendOutputsResponse)(nil), "walletrpc.SendOutputsResponse")
	proto.RegisterType((*EstimateFeeRequest)(nil), "walletrpc.EstimateFeeRequest")
	proto.RegisterType((*EstimateFeeResponse)(nil), "walletrpc.EstimateFeeResponse")
	proto.RegisterType((*PendingSweep)(nil), "walletrpc.PendingSweep")
	proto.RegisterType((*PendingSweepsRequest)(nil), "walletrpc.PendingSweepsRequest")
	proto.RegisterType((*PendingSweepsResponse)(nil), "walletrpc.PendingSweepsResponse")
	proto.RegisterType((*BumpFeeRequest)(nil), "walletrpc.BumpFeeRequest")
	proto.RegisterType((*BumpFeeResponse)(nil), "walletrpc.BumpFeeResponse")
	proto.RegisterEnum("walletrpc.WitnessType", WitnessType_name, WitnessType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletKitClient is the client API for WalletKit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletKitClient interface {
	// *
	// DeriveNextKey attempts to derive the *next* key within the key family
	// (account in BIP43) specified. This method should return the next external
	// child within this branch.
	DeriveNextKey(ctx context.Context, in *KeyReq, opts ...grpc.CallOption) (*signrpc.KeyDescriptor, error)
	// *
	// DeriveKey attempts to derive an arbitrary key specified by the passed
	// KeyLocator.
	DeriveKey(ctx context.Context, in *signrpc.KeyLocator, opts ...grpc.CallOption) (*signrpc.KeyDescriptor, error)
	// *
	// NextAddr returns the next unused address within the wallet.
	NextAddr(ctx context.Context, in *AddrRequest, opts ...grpc.CallOption) (*AddrResponse, error)
	// *
	// PublishTransaction attempts to publish the passed transaction to the
	// network. Once this returns without an error, the wallet will continually
	// attempt to re-broadcast the transaction on start up, until it enters the
	// chain.
	PublishTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*PublishResponse, error)
	// *
	// SendOutputs is similar to the existing sendmany call in Bitcoind, and
	// allows the caller to create a transaction that sends to several outputs at
	// once. This is ideal when wanting to batch create a set of transactions.
	SendOutputs(ctx context.Context, in *SendOutputsRequest, opts ...grpc.CallOption) (*SendOutputsResponse, error)
	// *
	// EstimateFee attempts to query the internal fee estimator of the wallet to
	// determine the fee (in atom/kB) to attach to a transaction in order to
	// achieve the confirmation target.
	EstimateFee(ctx context.Context, in *EstimateFeeRequest, opts ...grpc.CallOption) (*EstimateFeeResponse, error)
	//
	// PendingSweeps returns lists of on-chain outputs that lnd is currently
	// attempting to sweep within its central batching engine. Outputs with similar
	// fee rates are batched together in order to sweep them within a single
	// transaction.
	//
	// NOTE: Some of the fields within PendingSweepsRequest are not guaranteed to
	// remain supported. This is an advanced API that depends on the internals of
	// the UtxoSweeper, so things may change.
	PendingSweeps(ctx context.Context, in *PendingSweepsRequest, opts ...grpc.CallOption) (*PendingSweepsResponse, error)
	//
	// BumpFee bumps the fee of an arbitrary input within a transaction. This RPC
	// takes a different approach than bitcoind's bumpfee command. lnd has a
	// central batching engine in which inputs with similar fee rates are batched
	// together to save on transaction fees. Due to this, we cannot rely on
	// bumping the fee on a specific transaction, since transactions can change at
	// any point with the addition of new inputs. The list of inputs that
	// currently exist within lnd's central batching engine can be retrieved
	// through the PendingSweeps RPC.
	//
	// When bumping the fee of an input that currently exists within lnd's central
	// batching engine, a higher fee transaction will be created that replaces the
	// lower fee transaction through the Replace-By-Fee (RBF) policy. If it
	//
	// This RPC also serves useful when wanting to perform a Child-Pays-For-Parent
	// (CPFP), where the child transaction pays for its parent's fee. This can be
	// done by specifying an outpoint within the low fee transaction that is under
	// the control of the wallet.
	//
	// The fee preference can be expressed either as a specific fee rate or a delta
	// of blocks in which the output should be swept on-chain within. If a fee
	// preference is not explicitly specified, then an error is returned.
	//
	// Note that this RPC currently doesn't perform any validation checks on the
	// fee preference being provided. For now, the responsibility of ensuring that
	// the new fee preference is sufficient is delegated to the user.
	BumpFee(ctx context.Context, in *BumpFeeRequest, opts ...grpc.CallOption) (*BumpFeeResponse, error)
}

type walletKitClient struct {
	cc *grpc.ClientConn
}

func NewWalletKitClient(cc *grpc.ClientConn) WalletKitClient {
	return &walletKitClient{cc}
}

func (c *walletKitClient) DeriveNextKey(ctx context.Context, in *KeyReq, opts ...grpc.CallOption) (*signrpc.KeyDescriptor, error) {
	out := new(signrpc.KeyDescriptor)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletKit/DeriveNextKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletKitClient) DeriveKey(ctx context.Context, in *signrpc.KeyLocator, opts ...grpc.CallOption) (*signrpc.KeyDescriptor, error) {
	out := new(signrpc.KeyDescriptor)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletKit/DeriveKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletKitClient) NextAddr(ctx context.Context, in *AddrRequest, opts ...grpc.CallOption) (*AddrResponse, error) {
	out := new(AddrResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletKit/NextAddr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletKitClient) PublishTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletKit/PublishTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletKitClient) SendOutputs(ctx context.Context, in *SendOutputsRequest, opts ...grpc.CallOption) (*SendOutputsResponse, error) {
	out := new(SendOutputsResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletKit/SendOutputs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletKitClient) EstimateFee(ctx context.Context, in *EstimateFeeRequest, opts ...grpc.CallOption) (*EstimateFeeResponse, error) {
	out := new(EstimateFeeResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletKit/EstimateFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletKitClient) PendingSweeps(ctx context.Context, in *PendingSweepsRequest, opts ...grpc.CallOption) (*PendingSweepsResponse, error) {
	out := new(PendingSweepsResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletKit/PendingSweeps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletKitClient) BumpFee(ctx context.Context, in *BumpFeeRequest, opts ...grpc.CallOption) (*BumpFeeResponse, error) {
	out := new(BumpFeeResponse)
	err := c.cc.Invoke(ctx, "/walletrpc.WalletKit/BumpFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletKitServer is the server API for WalletKit service.
type WalletKitServer interface {
	// *
	// DeriveNextKey attempts to derive the *next* key within the key family
	// (account in BIP43) specified. This method should return the next external
	// child within this branch.
	DeriveNextKey(context.Context, *KeyReq) (*signrpc.KeyDescriptor, error)
	// *
	// DeriveKey attempts to derive an arbitrary key specified by the passed
	// KeyLocator.
	DeriveKey(context.Context, *signrpc.KeyLocator) (*signrpc.KeyDescriptor, error)
	// *
	// NextAddr returns the next unused address within the wallet.
	NextAddr(context.Context, *AddrRequest) (*AddrResponse, error)
	// *
	// PublishTransaction attempts to publish the passed transaction to the
	// network. Once this returns without an error, the wallet will continually
	// attempt to re-broadcast the transaction on start up, until it enters the
	// chain.
	PublishTransaction(context.Context, *Transaction) (*PublishResponse, error)
	// *
	// SendOutputs is similar to the existing sendmany call in Bitcoind, and
	// allows the caller to create a transaction that sends to several outputs at
	// once. This is ideal when wanting to batch create a set of transactions.
	SendOutputs(context.Context, *SendOutputsRequest) (*SendOutputsResponse, error)
	// *
	// EstimateFee attempts to query the internal fee estimator of the wallet to
	// determine the fee (in atom/kB) to attach to a transaction in order to
	// achieve the confirmation target.
	EstimateFee(context.Context, *EstimateFeeRequest) (*EstimateFeeResponse, error)
	//
	// PendingSweeps returns lists of on-chain outputs that lnd is currently
	// attempting to sweep within its central batching engine. Outputs with similar
	// fee rates are batched together in order to sweep them within a single
	// transaction.
	//
	// NOTE: Some of the fields within PendingSweepsRequest are not guaranteed to
	// remain supported. This is an advanced API that depends on the internals of
	// the UtxoSweeper, so things may change.
	PendingSweeps(context.Context, *PendingSweepsRequest) (*PendingSweepsResponse, error)
	//
	// BumpFee bumps the fee of an arbitrary input within a transaction. This RPC
	// takes a different approach than bitcoind's bumpfee command. lnd has a
	// central batching engine in which inputs with similar fee rates are batched
	// together to save on transaction fees. Due to this, we cannot rely on
	// bumping the fee on a specific transaction, since transactions can change at
	// any point with the addition of new inputs. The list of inputs that
	// currently exist within lnd's central batching engine can be retrieved
	// through the PendingSweeps RPC.
	//
	// When bumping the fee of an input that currently exists within lnd's central
	// batching engine, a higher fee transaction will be created that replaces the
	// lower fee transaction through the Replace-By-Fee (RBF) policy. If it
	//
	// This RPC also serves useful when wanting to perform a Child-Pays-For-Parent
	// (CPFP), where the child transaction pays for its parent's fee. This can be
	// done by specifying an outpoint within the low fee transaction that is under
	// the control of the wallet.
	//
	// The fee preference can be expressed either as a specific fee rate or a delta
	// of blocks in which the output should be swept on-chain within. If a fee
	// preference is not explicitly specified, then an error is returned.
	//
	// Note that this RPC currently doesn't perform any validation checks on the
	// fee preference being provided. For now, the responsibility of ensuring that
	// the new fee preference is sufficient is delegated to the user.
	BumpFee(context.Context, *BumpFeeRequest) (*BumpFeeResponse, error)
}

func RegisterWalletKitServer(s *grpc.Server, srv WalletKitServer) {
	s.RegisterService(&_WalletKit_serviceDesc, srv)
}

func _WalletKit_DeriveNextKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletKitServer).DeriveNextKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletKit/DeriveNextKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletKitServer).DeriveNextKey(ctx, req.(*KeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletKit_DeriveKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(signrpc.KeyLocator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletKitServer).DeriveKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletKit/DeriveKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletKitServer).DeriveKey(ctx, req.(*signrpc.KeyLocator))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletKit_NextAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletKitServer).NextAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletKit/NextAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletKitServer).NextAddr(ctx, req.(*AddrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletKit_PublishTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletKitServer).PublishTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletKit/PublishTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletKitServer).PublishTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletKit_SendOutputs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendOutputsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletKitServer).SendOutputs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletKit/SendOutputs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletKitServer).SendOutputs(ctx, req.(*SendOutputsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletKit_EstimateFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletKitServer).EstimateFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletKit/EstimateFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletKitServer).EstimateFee(ctx, req.(*EstimateFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletKit_PendingSweeps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PendingSweepsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletKitServer).PendingSweeps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletKit/PendingSweeps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletKitServer).PendingSweeps(ctx, req.(*PendingSweepsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletKit_BumpFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BumpFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletKitServer).BumpFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletrpc.WalletKit/BumpFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletKitServer).BumpFee(ctx, req.(*BumpFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletKit_serviceDesc = grpc.ServiceDesc{
	ServiceName: "walletrpc.WalletKit",
	HandlerType: (*WalletKitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeriveNextKey",
			Handler:    _WalletKit_DeriveNextKey_Handler,
		},
		{
			MethodName: "DeriveKey",
			Handler:    _WalletKit_DeriveKey_Handler,
		},
		{
			MethodName: "NextAddr",
			Handler:    _WalletKit_NextAddr_Handler,
		},
		{
			MethodName: "PublishTransaction",
			Handler:    _WalletKit_PublishTransaction_Handler,
		},
		{
			MethodName: "SendOutputs",
			Handler:    _WalletKit_SendOutputs_Handler,
		},
		{
			MethodName: "EstimateFee",
			Handler:    _WalletKit_EstimateFee_Handler,
		},
		{
			MethodName: "PendingSweeps",
			Handler:    _WalletKit_PendingSweeps_Handler,
		},
		{
			MethodName: "BumpFee",
			Handler:    _WalletKit_BumpFee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "walletrpc/walletkit.proto",
}

func init() {
	proto.RegisterFile("walletrpc/walletkit.proto", fileDescriptor_walletkit_17ae671db9771517)
}

var fileDescriptor_walletkit_17ae671db9771517 = []byte{
	// 985 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdd, 0x72, 0xe2, 0x36,
	0x14, 0x2e, 0x21, 0x21, 0xe1, 0x18, 0x88, 0xa3, 0xfc, 0x79, 0xd9, 0xdd, 0x86, 0xba, 0xed, 0x0e,
	0xb3, 0xed, 0x90, 0x99, 0xf4, 0x77, 0xda, 0x8b, 0x36, 0x21, 0xce, 0x24, 0x03, 0xc1, 0xd4, 0x76,
	0x36, 0xdd, 0xde, 0xa8, 0xc6, 0xd6, 0x12, 0x4f, 0xc0, 0xf6, 0xca, 0xa2, 0xc0, 0x5d, 0xef, 0xfa,
	0x02, 0x7d, 0x89, 0xbe, 0x42, 0x9f, 0xae, 0x63, 0xd9, 0x38, 0x32, 0x21, 0xd3, 0xd9, 0x2b, 0xc4,
	0xf7, 0x7d, 0xe7, 0xe8, 0xe8, 0xe8, 0xe8, 0x03, 0x78, 0x36, 0xb5, 0x47, 0x23, 0xc2, 0x68, 0xe8,
	0x1c, 0x27, 0xab, 0x7b, 0x8f, 0xb5, 0x42, 0x1a, 0xb0, 0x00, 0x95, 0x33, 0xaa, 0x5e, 0xa6, 0xa1,
	0x93, 0xa0, 0xf5, 0xbd, 0xc8, 0x1b, 0xfa, 0xb1, 0x3c, 0xfe, 0x24, 0x34, 0x41, 0xd5, 0x5f, 0xa0,
	0xd4, 0x21, 0x73, 0x83, 0xbc, 0x47, 0x4d, 0x90, 0xef, 0xc9, 0x1c, 0xbf, 0xf3, 0xfc, 0x21, 0xa1,
	0x38, 0xa4, 0x9e, 0xcf, 0x94, 0x42, 0xa3, 0xd0, 0xdc, 0x30, 0x6a, 0xf7, 0x64, 0x7e, 0xc1, 0xe1,
	0x7e, 0x8c, 0xa2, 0x97, 0x00, 0x5c, 0x69, 0x8f, 0xbd, 0xd1, 0x5c, 0x59, 0xe3, 0x9a, 0x72, 0xac,
	0xe1, 0x80, 0x5a, 0x05, 0xe9, 0xd4, 0x75, 0xa9, 0x41, 0xde, 0x4f, 0x48, 0xc4, 0x54, 0x15, 0x2a,
	0xc9, 0xd7, 0x28, 0x0c, 0xfc, 0x88, 0x20, 0x04, 0xeb, 0xb6, 0xeb, 0x52, 0x9e, 0xbb, 0x6c, 0xf0,
	0xb5, 0xfa, 0x19, 0x48, 0x16, 0xb5, 0xfd, 0xc8, 0x76, 0x98, 0x17, 0xf8, 0x68, 0x1f, 0x4a, 0x6c,
	0x86, 0xef, 0xc8, 0x8c, 0x8b, 0x2a, 0xc6, 0x06, 0x9b, 0x5d, 0x92, 0x99, 0xfa, 0x2d, 0x6c, 0xf7,
	0x27, 0x83, 0x91, 0x17, 0xdd, 0x65, 0xc9, 0x3e, 0x85, 0x6a, 0x98, 0x40, 0x98, 0x50, 0x1a, 0x2c,
	0xb2, 0x56, 0x52, 0x50, 0x8b, 0x31, 0xf5, 0x77, 0x40, 0x26, 0xf1, 0x5d, 0x7d, 0xc2, 0xc2, 0x09,
	0x8b, 0xd2, 0xba, 0x50, 0x03, 0x2a, 0x36, 0x0b, 0xc6, 0x11, 0x0e, 0x09, 0xc5, 0xf7, 0x03, 0x1e,
	0x59, 0x34, 0x80, 0x63, 0x7d, 0x42, 0x3b, 0x03, 0xd4, 0x84, 0xcd, 0x20, 0x89, 0x51, 0xd6, 0x1a,
	0xc5, 0xa6, 0x74, 0x52, 0x6b, 0xa5, 0x3d, 0x6c, 0x59, 0x33, 0x7d, 0xc2, 0x8c, 0x05, 0xad, 0x7e,
	0x09, 0xbb, 0xb9, 0x1d, 0xd2, 0xea, 0xf6, 0xa1, 0x44, 0xed, 0x29, 0x66, 0xd9, 0x39, 0xa8, 0x3d,
	0xb5, 0x66, 0xea, 0x37, 0x80, 0xb4, 0x88, 0x79, 0x63, 0x9b, 0x91, 0x0b, 0x42, 0x16, 0xf5, 0x1c,
	0x81, 0xe4, 0x04, 0xfe, 0x3b, 0xcc, 0x6c, 0x3a, 0x24, 0x8b, 0xd6, 0x43, 0x0c, 0x59, 0x1c, 0x51,
	0xbf, 0x83, 0xdd, 0x5c, 0x58, 0xba, 0xc9, 0xff, 0x9e, 0x43, 0xfd, 0x67, 0x0d, 0x2a, 0x7d, 0xe2,
	0xbb, 0x9e, 0x3f, 0x34, 0xa7, 0x84, 0x84, 0xe8, 0x0b, 0xd8, 0x8a, 0x2b, 0x0f, 0x16, 0x57, 0x2c,
	0x9d, 0x6c, 0xb7, 0x46, 0xfc, 0x5c, 0xfa, 0x84, 0xf5, 0x63, 0xd8, 0xc8, 0x04, 0xe8, 0x07, 0xa8,
	0x4c, 0x3d, 0xe6, 0x93, 0x28, 0xc2, 0x6c, 0x1e, 0x12, 0x7e, 0xdf, 0xb5, 0x93, 0x83, 0x56, 0x36,
	0x64, 0xad, 0xdb, 0x84, 0xb6, 0xe6, 0x21, 0x31, 0x72, 0x5a, 0xa4, 0x42, 0xc5, 0x1e, 0x07, 0x13,
	0x9f, 0x61, 0x5e, 0x8e, 0x52, 0x6c, 0x14, 0x9a, 0x55, 0x23, 0x87, 0xa1, 0x57, 0x50, 0x7b, 0xa8,
	0x7f, 0x30, 0x67, 0x44, 0x59, 0xe7, 0xaa, 0x25, 0x14, 0xb5, 0x00, 0x0d, 0x68, 0x60, 0xbb, 0x8e,
	0x1d, 0xc5, 0xa1, 0x8c, 0x8c, 0x43, 0x16, 0x29, 0x1b, 0x5c, 0xbb, 0x82, 0x41, 0x5f, 0xc3, 0xbe,
	0x4f, 0x66, 0x0c, 0x3f, 0x50, 0x77, 0xc4, 0x1b, 0xde, 0x31, 0xa5, 0xc4, 0x43, 0x56, 0x93, 0xea,
	0x01, 0xec, 0x89, 0xad, 0x5a, 0x4c, 0x8b, 0xfa, 0x2b, 0xec, 0x2f, 0xe1, 0x69, 0xfb, 0x7f, 0x82,
	0x5a, 0x98, 0x10, 0x38, 0xe2, 0x8c, 0x52, 0xe0, 0xb3, 0x72, 0x28, 0x34, 0x48, 0x8c, 0x34, 0x96,
	0xe4, 0xea, 0x5f, 0x05, 0xa8, 0x9d, 0x4d, 0xc6, 0xa1, 0x30, 0x0a, 0x1f, 0x74, 0x3f, 0x0d, 0x90,
	0x92, 0x91, 0xc1, 0xf1, 0xac, 0xf0, 0xeb, 0xa9, 0x1a, 0x22, 0xb4, 0xa2, 0xc3, 0xc5, 0x55, 0x1d,
	0x56, 0x77, 0x60, 0x3b, 0x2b, 0x24, 0x39, 0xdd, 0xeb, 0xbf, 0x8b, 0x20, 0x09, 0xd7, 0x8b, 0x76,
	0x61, 0xfb, 0xa6, 0xd7, 0xe9, 0xe9, 0xb7, 0x3d, 0x7c, 0x7b, 0x65, 0xf5, 0x34, 0xd3, 0x94, 0x3f,
	0x42, 0x0a, 0xec, 0xb5, 0xf5, 0xeb, 0xeb, 0x2b, 0xeb, 0x5a, 0xeb, 0x59, 0xd8, 0xba, 0xba, 0xd6,
	0x70, 0x57, 0x6f, 0x77, 0xe4, 0x02, 0x3a, 0x84, 0x5d, 0x81, 0xe9, 0xe9, 0xf8, 0x5c, 0xeb, 0x9e,
	0xbe, 0x95, 0xd7, 0xd0, 0x3e, 0xec, 0x08, 0x84, 0xa1, 0xbd, 0xd1, 0x3b, 0x9a, 0x5c, 0x8c, 0xf5,
	0x97, 0x56, 0xb7, 0x8d, 0xf5, 0x8b, 0x0b, 0xcd, 0xd0, 0xce, 0x17, 0xc4, 0x7a, 0xbc, 0x05, 0x27,
	0x4e, 0xdb, 0x6d, 0xad, 0x6f, 0x3d, 0x30, 0x1b, 0xe8, 0x73, 0xf8, 0x24, 0x17, 0x12, 0x6f, 0xaf,
	0xdf, 0x58, 0xd8, 0xd4, 0xda, 0x7a, 0xef, 0x1c, 0x77, 0xb5, 0x37, 0x5a, 0x57, 0x2e, 0xa1, 0x57,
	0xa0, 0xe6, 0x13, 0x98, 0x37, 0xed, 0xb6, 0x66, 0x9a, 0x79, 0xdd, 0x26, 0x3a, 0x82, 0xe7, 0x4b,
	0x15, 0x5c, 0xeb, 0x96, 0xb6, 0xc8, 0x2a, 0x6f, 0xa1, 0x06, 0xbc, 0x58, 0xae, 0x84, 0x2b, 0xd2,
	0x7c, 0x72, 0x19, 0xbd, 0x00, 0x85, 0x2b, 0xc4, 0xcc, 0x8b, 0x7a, 0x01, 0xed, 0x81, 0x9c, 0x76,
	0x0e, 0x77, 0xb4, 0xb7, 0xf8, 0xf2, 0xd4, 0xbc, 0x94, 0x25, 0xf4, 0x1c, 0x0e, 0x7b, 0x9a, 0x19,
	0xa7, 0x7b, 0x44, 0x56, 0x90, 0x0c, 0x52, 0xff, 0xe6, 0x2c, 0x03, 0xfe, 0x2c, 0x9c, 0xfc, 0xbb,
	0x0e, 0xe5, 0x5b, 0x3e, 0x5e, 0x1d, 0x2f, 0x7e, 0xa1, 0xd5, 0x73, 0x42, 0xbd, 0x3f, 0x48, 0x8f,
	0xcc, 0x58, 0x87, 0xcc, 0xd1, 0x8e, 0x30, 0x7b, 0x89, 0xbb, 0xd7, 0x0f, 0x32, 0xeb, 0xea, 0x90,
	0xf9, 0x39, 0x89, 0x1c, 0xea, 0x85, 0x2c, 0xa0, 0xe8, 0x7b, 0x28, 0x27, 0xb1, 0x71, 0xdc, 0xae,
	0x28, 0xea, 0x06, 0x8e, 0xcd, 0x02, 0xfa, 0x64, 0xe4, 0x8f, 0xb0, 0x15, 0xef, 0x17, 0x7b, 0x3b,
	0x12, 0xdd, 0x40, 0xf0, 0xfe, 0xfa, 0xe1, 0x23, 0x3c, 0x7d, 0x35, 0x97, 0x80, 0x52, 0x2b, 0x17,
	0x7d, 0x5f, 0x4c, 0x23, 0xe0, 0xf5, 0xba, 0xf8, 0x96, 0x96, 0x7e, 0x01, 0xba, 0x20, 0x09, 0xd6,
	0x8b, 0x5e, 0x0a, 0xd2, 0xc7, 0xa6, 0x5f, 0xff, 0xf8, 0x29, 0xfa, 0x21, 0x9b, 0xe0, 0xb1, 0xb9,
	0x6c, 0x8f, 0x2d, 0x3b, 0x97, 0x6d, 0x95, 0x35, 0x1b, 0x50, 0xcd, 0x99, 0x06, 0x3a, 0x7a, 0xc2,
	0x14, 0xb2, 0xfa, 0x1a, 0x4f, 0x0b, 0xd2, 0x9c, 0x3f, 0xc3, 0x66, 0xfa, 0x48, 0xd1, 0x33, 0x41,
	0x9c, 0x77, 0x90, 0x5c, 0xc7, 0x96, 0xde, 0xf4, 0xd9, 0xeb, 0xdf, 0x9a, 0x43, 0x8f, 0xdd, 0x4d,
	0x06, 0x2d, 0x27, 0x18, 0x1f, 0xbb, 0xc4, 0xa1, 0xc4, 0x3d, 0x76, 0x1d, 0x3a, 0xf2, 0xdd, 0x63,
	0xee, 0x32, 0xc7, 0x59, 0xec, 0xa0, 0xc4, 0xff, 0x25, 0x7c, 0xf5, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa4, 0xb5, 0x47, 0x97, 0x6e, 0x08, 0x00, 0x00,
}
