// Code generated by protoc-gen-go. DO NOT EDIT.
// source: verrpc/verrpc.proto

package verrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_494312204cefa0e6, []int{0}
}

func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRequest.Unmarshal(m, b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
}
func (m *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(m, src)
}
func (m *VersionRequest) XXX_Size() int {
	return xxx_messageInfo_VersionRequest.Size(m)
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

type Version struct {
	/// A verbose description of the daemon's commit.
	Commit string `protobuf:"bytes,1,opt,name=commit,proto3" json:"commit,omitempty"`
	/// The SHA1 commit hash that the daemon is compiled with.
	CommitHash string `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	/// The semantic version.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	/// The major application version.
	AppMajor uint32 `protobuf:"varint,4,opt,name=app_major,json=appMajor,proto3" json:"app_major,omitempty"`
	/// The minor application version.
	AppMinor uint32 `protobuf:"varint,5,opt,name=app_minor,json=appMinor,proto3" json:"app_minor,omitempty"`
	/// The application patch number.
	AppPatch uint32 `protobuf:"varint,6,opt,name=app_patch,json=appPatch,proto3" json:"app_patch,omitempty"`
	/// The application pre-release modifier, possibly empty.
	AppPreRelease string `protobuf:"bytes,7,opt,name=app_pre_release,json=appPreRelease,proto3" json:"app_pre_release,omitempty"`
	/// The list of build tags that were supplied during comilation.
	BuildTags []string `protobuf:"bytes,8,rep,name=build_tags,json=buildTags,proto3" json:"build_tags,omitempty"`
	/// The version of go that compiled the executable.
	GoVersion            string   `protobuf:"bytes,9,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_494312204cefa0e6, []int{1}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

func (m *Version) GetCommitHash() string {
	if m != nil {
		return m.CommitHash
	}
	return ""
}

func (m *Version) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Version) GetAppMajor() uint32 {
	if m != nil {
		return m.AppMajor
	}
	return 0
}

func (m *Version) GetAppMinor() uint32 {
	if m != nil {
		return m.AppMinor
	}
	return 0
}

func (m *Version) GetAppPatch() uint32 {
	if m != nil {
		return m.AppPatch
	}
	return 0
}

func (m *Version) GetAppPreRelease() string {
	if m != nil {
		return m.AppPreRelease
	}
	return ""
}

func (m *Version) GetBuildTags() []string {
	if m != nil {
		return m.BuildTags
	}
	return nil
}

func (m *Version) GetGoVersion() string {
	if m != nil {
		return m.GoVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionRequest)(nil), "verrpc.VersionRequest")
	proto.RegisterType((*Version)(nil), "verrpc.Version")
}

func init() { proto.RegisterFile("verrpc/verrpc.proto", fileDescriptor_494312204cefa0e6) }

var fileDescriptor_494312204cefa0e6 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0xe9, 0xa6, 0xed, 0x72, 0x64, 0x4e, 0x22, 0x48, 0x50, 0xc4, 0xb2, 0x0b, 0xe9, 0xd5,
	0x04, 0xc5, 0x17, 0xf0, 0x46, 0x6f, 0x04, 0x29, 0xe2, 0x6d, 0xc9, 0xea, 0xa1, 0xad, 0xac, 0x4b,
	0x3c, 0xc9, 0xf6, 0x2e, 0xbe, 0xad, 0xe4, 0x4f, 0x2b, 0xee, 0xaa, 0xe7, 0xf7, 0xfd, 0xca, 0x49,
	0xf8, 0x02, 0xe7, 0x7b, 0x24, 0xd2, 0xf5, 0x5d, 0xf8, 0xac, 0x34, 0x29, 0xab, 0x78, 0x1a, 0x68,
	0x79, 0x06, 0xa7, 0x1f, 0x48, 0xa6, 0x53, 0xdb, 0x12, 0xbf, 0x77, 0x68, 0xec, 0xf2, 0x67, 0x02,
	0x59, 0x8c, 0xf8, 0x05, 0xa4, 0xb5, 0xea, 0xfb, 0xce, 0x8a, 0x24, 0x4f, 0x0a, 0x56, 0x46, 0xe2,
	0x37, 0x70, 0x12, 0xa6, 0xaa, 0x95, 0xa6, 0x15, 0x13, 0x2f, 0x21, 0x44, 0x2f, 0xd2, 0xb4, 0x5c,
	0x40, 0xb6, 0x0f, 0x3b, 0xc4, 0xd4, 0xcb, 0x01, 0xf9, 0x15, 0x30, 0xa9, 0x75, 0xd5, 0xcb, 0x2f,
	0x45, 0xe2, 0x28, 0x4f, 0x8a, 0x79, 0x39, 0x93, 0x5a, 0xbf, 0x3a, 0x1e, 0x65, 0xb7, 0x55, 0x24,
	0x8e, 0xff, 0xa4, 0xe3, 0x41, 0x6a, 0x69, 0xeb, 0x56, 0xa4, 0xa3, 0x7c, 0x73, 0xcc, 0x6f, 0x61,
	0xe1, 0x25, 0x61, 0x45, 0xb8, 0x41, 0x69, 0x50, 0x64, 0xfe, 0xe0, 0xb9, 0xfb, 0x85, 0xb0, 0x0c,
	0x21, 0xbf, 0x06, 0x58, 0xef, 0xba, 0xcd, 0x67, 0x65, 0x65, 0x63, 0xc4, 0x2c, 0x9f, 0x16, 0xac,
	0x64, 0x3e, 0x79, 0x97, 0x8d, 0x71, 0xba, 0x51, 0xd5, 0x70, 0x75, 0xe6, 0x37, 0xb0, 0x46, 0xc5,
	0x3e, 0xee, 0x9f, 0x80, 0xc5, 0x11, 0x89, 0x3f, 0x02, 0x3c, 0xa3, 0x1d, 0xab, 0x5a, 0xc5, 0x7e,
	0xff, 0xd7, 0x79, 0xb9, 0x38, 0xc8, 0xd7, 0xa9, 0x7f, 0x80, 0x87, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xca, 0x3a, 0xba, 0x83, 0x97, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VersionerClient is the client API for Versioner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VersionerClient interface {
	GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*Version, error)
}

type versionerClient struct {
	cc *grpc.ClientConn
}

func NewVersionerClient(cc *grpc.ClientConn) VersionerClient {
	return &versionerClient{cc}
}

func (c *versionerClient) GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*Version, error) {
	out := new(Version)
	err := c.cc.Invoke(ctx, "/verrpc.Versioner/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VersionerServer is the server API for Versioner service.
type VersionerServer interface {
	GetVersion(context.Context, *VersionRequest) (*Version, error)
}

// UnimplementedVersionerServer can be embedded to have forward compatible implementations.
type UnimplementedVersionerServer struct {
}

func (*UnimplementedVersionerServer) GetVersion(ctx context.Context, req *VersionRequest) (*Version, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}

func RegisterVersionerServer(s *grpc.Server, srv VersionerServer) {
	s.RegisterService(&_Versioner_serviceDesc, srv)
}

func _Versioner_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionerServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verrpc.Versioner/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionerServer).GetVersion(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Versioner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "verrpc.Versioner",
	HandlerType: (*VersionerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _Versioner_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verrpc/verrpc.proto",
}
