// Code generated by protoc-gen-go. DO NOT EDIT.
// source: routerrpc/router.proto

package routerrpc // import "github.com/decred/dcrlnd/lnrpc/routerrpc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import lnrpc "github.com/decred/dcrlnd/lnrpc"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Failure_FailureCode int32

const (
	// *
	// The numbers assigned in this enumeration match the failure codes as
	// defined in BOLT #4. Because protobuf 3 requires enums to start with 0,
	// a RESERVED value is added.
	Failure_RESERVED                         Failure_FailureCode = 0
	Failure_UNKNOWN_PAYMENT_HASH             Failure_FailureCode = 1
	Failure_INCORRECT_PAYMENT_AMOUNT         Failure_FailureCode = 2
	Failure_FINAL_INCORRECT_CLTV_EXPIRY      Failure_FailureCode = 3
	Failure_FINAL_INCORRECT_HTLC_AMOUNT      Failure_FailureCode = 4
	Failure_FINAL_EXPIRY_TOO_SOON            Failure_FailureCode = 5
	Failure_INVALID_REALM                    Failure_FailureCode = 6
	Failure_EXPIRY_TOO_SOON                  Failure_FailureCode = 7
	Failure_INVALID_ONION_VERSION            Failure_FailureCode = 8
	Failure_INVALID_ONION_HMAC               Failure_FailureCode = 9
	Failure_INVALID_ONION_KEY                Failure_FailureCode = 10
	Failure_AMOUNT_BELOW_MINIMUM             Failure_FailureCode = 11
	Failure_FEE_INSUFFICIENT                 Failure_FailureCode = 12
	Failure_INCORRECT_CLTV_EXPIRY            Failure_FailureCode = 13
	Failure_CHANNEL_DISABLED                 Failure_FailureCode = 14
	Failure_TEMPORARY_CHANNEL_FAILURE        Failure_FailureCode = 15
	Failure_REQUIRED_NODE_FEATURE_MISSING    Failure_FailureCode = 16
	Failure_REQUIRED_CHANNEL_FEATURE_MISSING Failure_FailureCode = 17
	Failure_UNKNOWN_NEXT_PEER                Failure_FailureCode = 18
	Failure_TEMPORARY_NODE_FAILURE           Failure_FailureCode = 19
	Failure_PERMANENT_NODE_FAILURE           Failure_FailureCode = 20
	Failure_PERMANENT_CHANNEL_FAILURE        Failure_FailureCode = 21
)

var Failure_FailureCode_name = map[int32]string{
	0:  "RESERVED",
	1:  "UNKNOWN_PAYMENT_HASH",
	2:  "INCORRECT_PAYMENT_AMOUNT",
	3:  "FINAL_INCORRECT_CLTV_EXPIRY",
	4:  "FINAL_INCORRECT_HTLC_AMOUNT",
	5:  "FINAL_EXPIRY_TOO_SOON",
	6:  "INVALID_REALM",
	7:  "EXPIRY_TOO_SOON",
	8:  "INVALID_ONION_VERSION",
	9:  "INVALID_ONION_HMAC",
	10: "INVALID_ONION_KEY",
	11: "AMOUNT_BELOW_MINIMUM",
	12: "FEE_INSUFFICIENT",
	13: "INCORRECT_CLTV_EXPIRY",
	14: "CHANNEL_DISABLED",
	15: "TEMPORARY_CHANNEL_FAILURE",
	16: "REQUIRED_NODE_FEATURE_MISSING",
	17: "REQUIRED_CHANNEL_FEATURE_MISSING",
	18: "UNKNOWN_NEXT_PEER",
	19: "TEMPORARY_NODE_FAILURE",
	20: "PERMANENT_NODE_FAILURE",
	21: "PERMANENT_CHANNEL_FAILURE",
}
var Failure_FailureCode_value = map[string]int32{
	"RESERVED":                         0,
	"UNKNOWN_PAYMENT_HASH":             1,
	"INCORRECT_PAYMENT_AMOUNT":         2,
	"FINAL_INCORRECT_CLTV_EXPIRY":      3,
	"FINAL_INCORRECT_HTLC_AMOUNT":      4,
	"FINAL_EXPIRY_TOO_SOON":            5,
	"INVALID_REALM":                    6,
	"EXPIRY_TOO_SOON":                  7,
	"INVALID_ONION_VERSION":            8,
	"INVALID_ONION_HMAC":               9,
	"INVALID_ONION_KEY":                10,
	"AMOUNT_BELOW_MINIMUM":             11,
	"FEE_INSUFFICIENT":                 12,
	"INCORRECT_CLTV_EXPIRY":            13,
	"CHANNEL_DISABLED":                 14,
	"TEMPORARY_CHANNEL_FAILURE":        15,
	"REQUIRED_NODE_FEATURE_MISSING":    16,
	"REQUIRED_CHANNEL_FEATURE_MISSING": 17,
	"UNKNOWN_NEXT_PEER":                18,
	"TEMPORARY_NODE_FAILURE":           19,
	"PERMANENT_NODE_FAILURE":           20,
	"PERMANENT_CHANNEL_FAILURE":        21,
}

func (x Failure_FailureCode) String() string {
	return proto.EnumName(Failure_FailureCode_name, int32(x))
}
func (Failure_FailureCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_router_21c2826f7d4d1264, []int{6, 0}
}

type PaymentRequest struct {
	// *
	// A serialized BOLT-11 payment request that contains all information
	// required to dispatch the payment. If the pay req is invalid, or expired,
	// an error will be returned.
	PayReq string `protobuf:"bytes,1,opt,name=pay_req,json=payReq,proto3" json:"pay_req,omitempty"`
	// *
	// An absolute limit on the highest fee we should pay when looking for a route
	// to the destination. Routes with fees higher than this will be ignored, if
	// there are no routes with a fee below this amount, an error will be
	// returned.
	FeeLimitAtoms int64 `protobuf:"varint,2,opt,name=fee_limit_atoms,json=feeLimitAtoms,proto3" json:"fee_limit_atoms,omitempty"`
	// *
	// An absolute limit on the cumulative CLTV value along the route for this
	// payment. Routes with total CLTV values higher than this will be ignored,
	// if there are no routes with a CLTV value below this amount, an error will
	// be returned.
	CltvLimit int32 `protobuf:"varint,3,opt,name=cltv_limit,json=cltvLimit,proto3" json:"cltv_limit,omitempty"`
	// *
	// An upper limit on the amount of time we should spend when attempting to
	// fulfill the payment. This is expressed in seconds. If we cannot make a
	// successful payment within this time frame, an error will be returned.
	TimeoutSeconds int32 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// *
	// The channel id of the channel that must be taken to the first hop. If zero,
	// any channel may be used.
	OutgoingChannelId    int64    `protobuf:"varint,5,opt,name=outgoing_channel_id,json=outgoingChannelId,proto3" json:"outgoing_channel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentRequest) Reset()         { *m = PaymentRequest{} }
func (m *PaymentRequest) String() string { return proto.CompactTextString(m) }
func (*PaymentRequest) ProtoMessage()    {}
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_router_21c2826f7d4d1264, []int{0}
}
func (m *PaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentRequest.Unmarshal(m, b)
}
func (m *PaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentRequest.Marshal(b, m, deterministic)
}
func (dst *PaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentRequest.Merge(dst, src)
}
func (m *PaymentRequest) XXX_Size() int {
	return xxx_messageInfo_PaymentRequest.Size(m)
}
func (m *PaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentRequest proto.InternalMessageInfo

func (m *PaymentRequest) GetPayReq() string {
	if m != nil {
		return m.PayReq
	}
	return ""
}

func (m *PaymentRequest) GetFeeLimitAtoms() int64 {
	if m != nil {
		return m.FeeLimitAtoms
	}
	return 0
}

func (m *PaymentRequest) GetCltvLimit() int32 {
	if m != nil {
		return m.CltvLimit
	}
	return 0
}

func (m *PaymentRequest) GetTimeoutSeconds() int32 {
	if m != nil {
		return m.TimeoutSeconds
	}
	return 0
}

func (m *PaymentRequest) GetOutgoingChannelId() int64 {
	if m != nil {
		return m.OutgoingChannelId
	}
	return 0
}

type PaymentResponse struct {
	// *
	// The payment hash that we paid to. Provided so callers are able to map
	// responses (which may be streaming) back to their original requests.
	PayHash []byte `protobuf:"bytes,1,opt,name=pay_hash,json=payHash,proto3" json:"pay_hash,omitempty"`
	// *
	// The pre-image of the payment successfully completed.
	PreImage []byte `protobuf:"bytes,2,opt,name=pre_image,json=preImage,proto3" json:"pre_image,omitempty"`
	// *
	// If not an empty string, then a string representation of the payment error.
	PaymentErr           string   `protobuf:"bytes,3,opt,name=payment_err,json=paymentErr,proto3" json:"payment_err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentResponse) Reset()         { *m = PaymentResponse{} }
func (m *PaymentResponse) String() string { return proto.CompactTextString(m) }
func (*PaymentResponse) ProtoMessage()    {}
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_router_21c2826f7d4d1264, []int{1}
}
func (m *PaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentResponse.Unmarshal(m, b)
}
func (m *PaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentResponse.Marshal(b, m, deterministic)
}
func (dst *PaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentResponse.Merge(dst, src)
}
func (m *PaymentResponse) XXX_Size() int {
	return xxx_messageInfo_PaymentResponse.Size(m)
}
func (m *PaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentResponse proto.InternalMessageInfo

func (m *PaymentResponse) GetPayHash() []byte {
	if m != nil {
		return m.PayHash
	}
	return nil
}

func (m *PaymentResponse) GetPreImage() []byte {
	if m != nil {
		return m.PreImage
	}
	return nil
}

func (m *PaymentResponse) GetPaymentErr() string {
	if m != nil {
		return m.PaymentErr
	}
	return ""
}

type RouteFeeRequest struct {
	// *
	// The destination once wishes to obtain a routing fee quote to.
	Dest []byte `protobuf:"bytes,1,opt,name=dest,proto3" json:"dest,omitempty"`
	// *
	// The amount one wishes to send to the target destination.
	AmtAtoms             int64    `protobuf:"varint,2,opt,name=amt_atoms,json=amtAtoms,proto3" json:"amt_atoms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteFeeRequest) Reset()         { *m = RouteFeeRequest{} }
func (m *RouteFeeRequest) String() string { return proto.CompactTextString(m) }
func (*RouteFeeRequest) ProtoMessage()    {}
func (*RouteFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_router_21c2826f7d4d1264, []int{2}
}
func (m *RouteFeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteFeeRequest.Unmarshal(m, b)
}
func (m *RouteFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteFeeRequest.Marshal(b, m, deterministic)
}
func (dst *RouteFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteFeeRequest.Merge(dst, src)
}
func (m *RouteFeeRequest) XXX_Size() int {
	return xxx_messageInfo_RouteFeeRequest.Size(m)
}
func (m *RouteFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RouteFeeRequest proto.InternalMessageInfo

func (m *RouteFeeRequest) GetDest() []byte {
	if m != nil {
		return m.Dest
	}
	return nil
}

func (m *RouteFeeRequest) GetAmtAtoms() int64 {
	if m != nil {
		return m.AmtAtoms
	}
	return 0
}

type RouteFeeResponse struct {
	// *
	// A lower bound of the estimated fee to the target destination within the
	// network, expressed in milli-satoshis.
	RoutingFeeMatoms int64 `protobuf:"varint,1,opt,name=routing_fee_matoms,json=routingFeeMatoms,proto3" json:"routing_fee_matoms,omitempty"`
	// *
	// An estimate of the worst case time delay that can occur. Note that callers
	// will still need to factor in the final CLTV delta of the last hop into this
	// value.
	TimeLockDelay        int64    `protobuf:"varint,2,opt,name=time_lock_delay,json=timeLockDelay,proto3" json:"time_lock_delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteFeeResponse) Reset()         { *m = RouteFeeResponse{} }
func (m *RouteFeeResponse) String() string { return proto.CompactTextString(m) }
func (*RouteFeeResponse) ProtoMessage()    {}
func (*RouteFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_router_21c2826f7d4d1264, []int{3}
}
func (m *RouteFeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteFeeResponse.Unmarshal(m, b)
}
func (m *RouteFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteFeeResponse.Marshal(b, m, deterministic)
}
func (dst *RouteFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteFeeResponse.Merge(dst, src)
}
func (m *RouteFeeResponse) XXX_Size() int {
	return xxx_messageInfo_RouteFeeResponse.Size(m)
}
func (m *RouteFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RouteFeeResponse proto.InternalMessageInfo

func (m *RouteFeeResponse) GetRoutingFeeMatoms() int64 {
	if m != nil {
		return m.RoutingFeeMatoms
	}
	return 0
}

func (m *RouteFeeResponse) GetTimeLockDelay() int64 {
	if m != nil {
		return m.TimeLockDelay
	}
	return 0
}

type SendToRouteRequest struct {
	// / The payment hash to use for the HTLC.
	PaymentHash []byte `protobuf:"bytes,1,opt,name=payment_hash,json=paymentHash,proto3" json:"payment_hash,omitempty"`
	// / Route that should be used to attempt to complete the payment.
	Route                *lnrpc.Route `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendToRouteRequest) Reset()         { *m = SendToRouteRequest{} }
func (m *SendToRouteRequest) String() string { return proto.CompactTextString(m) }
func (*SendToRouteRequest) ProtoMessage()    {}
func (*SendToRouteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_router_21c2826f7d4d1264, []int{4}
}
func (m *SendToRouteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendToRouteRequest.Unmarshal(m, b)
}
func (m *SendToRouteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendToRouteRequest.Marshal(b, m, deterministic)
}
func (dst *SendToRouteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendToRouteRequest.Merge(dst, src)
}
func (m *SendToRouteRequest) XXX_Size() int {
	return xxx_messageInfo_SendToRouteRequest.Size(m)
}
func (m *SendToRouteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendToRouteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendToRouteRequest proto.InternalMessageInfo

func (m *SendToRouteRequest) GetPaymentHash() []byte {
	if m != nil {
		return m.PaymentHash
	}
	return nil
}

func (m *SendToRouteRequest) GetRoute() *lnrpc.Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type SendToRouteResponse struct {
	// / The preimage obtained by making the payment.
	Preimage []byte `protobuf:"bytes,1,opt,name=preimage,proto3" json:"preimage,omitempty"`
	// / The failure message in case the payment failed.
	Failure              *Failure `protobuf:"bytes,2,opt,name=failure,proto3" json:"failure,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendToRouteResponse) Reset()         { *m = SendToRouteResponse{} }
func (m *SendToRouteResponse) String() string { return proto.CompactTextString(m) }
func (*SendToRouteResponse) ProtoMessage()    {}
func (*SendToRouteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_router_21c2826f7d4d1264, []int{5}
}
func (m *SendToRouteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendToRouteResponse.Unmarshal(m, b)
}
func (m *SendToRouteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendToRouteResponse.Marshal(b, m, deterministic)
}
func (dst *SendToRouteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendToRouteResponse.Merge(dst, src)
}
func (m *SendToRouteResponse) XXX_Size() int {
	return xxx_messageInfo_SendToRouteResponse.Size(m)
}
func (m *SendToRouteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendToRouteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendToRouteResponse proto.InternalMessageInfo

func (m *SendToRouteResponse) GetPreimage() []byte {
	if m != nil {
		return m.Preimage
	}
	return nil
}

func (m *SendToRouteResponse) GetFailure() *Failure {
	if m != nil {
		return m.Failure
	}
	return nil
}

type Failure struct {
	// / Failure code as defined in the Lightning spec
	Code Failure_FailureCode `protobuf:"varint,1,opt,name=code,proto3,enum=routerrpc.Failure_FailureCode" json:"code,omitempty"`
	// *
	// The node pubkey of the intermediate or final node that generated the failure
	// message.
	FailureSourcePubkey []byte `protobuf:"bytes,2,opt,name=failure_source_pubkey,json=failureSourcePubkey,proto3" json:"failure_source_pubkey,omitempty"`
	// / An optional channel update message.
	ChannelUpdate *ChannelUpdate `protobuf:"bytes,3,opt,name=channel_update,json=channelUpdate,proto3" json:"channel_update,omitempty"`
	// / A failure type-dependent htlc value.
	HtlcMAtoms uint64 `protobuf:"varint,4,opt,name=htlc_m_atoms,json=htlcMAtoms,proto3" json:"htlc_m_atoms,omitempty"`
	// / The sha256 sum of the onion payload.
	OnionSha_256 []byte `protobuf:"bytes,5,opt,name=onion_sha_256,json=onionSha256,proto3" json:"onion_sha_256,omitempty"`
	// / A failure type-dependent cltv expiry value.
	CltvExpiry uint32 `protobuf:"varint,6,opt,name=cltv_expiry,json=cltvExpiry,proto3" json:"cltv_expiry,omitempty"`
	// / A failure type-dependent flags value.
	Flags                uint32   `protobuf:"varint,7,opt,name=flags,proto3" json:"flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Failure) Reset()         { *m = Failure{} }
func (m *Failure) String() string { return proto.CompactTextString(m) }
func (*Failure) ProtoMessage()    {}
func (*Failure) Descriptor() ([]byte, []int) {
	return fileDescriptor_router_21c2826f7d4d1264, []int{6}
}
func (m *Failure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Failure.Unmarshal(m, b)
}
func (m *Failure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Failure.Marshal(b, m, deterministic)
}
func (dst *Failure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Failure.Merge(dst, src)
}
func (m *Failure) XXX_Size() int {
	return xxx_messageInfo_Failure.Size(m)
}
func (m *Failure) XXX_DiscardUnknown() {
	xxx_messageInfo_Failure.DiscardUnknown(m)
}

var xxx_messageInfo_Failure proto.InternalMessageInfo

func (m *Failure) GetCode() Failure_FailureCode {
	if m != nil {
		return m.Code
	}
	return Failure_RESERVED
}

func (m *Failure) GetFailureSourcePubkey() []byte {
	if m != nil {
		return m.FailureSourcePubkey
	}
	return nil
}

func (m *Failure) GetChannelUpdate() *ChannelUpdate {
	if m != nil {
		return m.ChannelUpdate
	}
	return nil
}

func (m *Failure) GetHtlcMAtoms() uint64 {
	if m != nil {
		return m.HtlcMAtoms
	}
	return 0
}

func (m *Failure) GetOnionSha_256() []byte {
	if m != nil {
		return m.OnionSha_256
	}
	return nil
}

func (m *Failure) GetCltvExpiry() uint32 {
	if m != nil {
		return m.CltvExpiry
	}
	return 0
}

func (m *Failure) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

type ChannelUpdate struct {
	// *
	// The signature that validates the announced data and proves the ownership
	// of node id.
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// *
	// The target chain that this channel was opened within. This value
	// should be the genesis hash of the target chain. Along with the short
	// channel ID, this uniquely identifies the channel globally in a
	// blockchain.
	ChainHash []byte `protobuf:"bytes,2,opt,name=chain_hash,json=chainHash,proto3" json:"chain_hash,omitempty"`
	// *
	// The unique description of the funding transaction.
	ChanId uint64 `protobuf:"varint,3,opt,name=chan_id,json=chanId,proto3" json:"chan_id,omitempty"`
	// *
	// A timestamp that allows ordering in the case of multiple announcements.
	// We should ignore the message if timestamp is not greater than the
	// last-received.
	Timestamp uint32 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// *
	// The bitfield that describes whether optional fields are present in this
	// update. Currently, the least-significant bit must be set to 1 if the
	// optional field MaxHtlc is present.
	MessageFlags uint32 `protobuf:"varint,10,opt,name=message_flags,json=messageFlags,proto3" json:"message_flags,omitempty"`
	// *
	// The bitfield that describes additional meta-data concerning how the
	// update is to be interpreted. Currently, the least-significant bit must be
	// set to 0 if the creating node corresponds to the first node in the
	// previously sent channel announcement and 1 otherwise. If the second bit
	// is set, then the channel is set to be disabled.
	ChannelFlags uint32 `protobuf:"varint,5,opt,name=channel_flags,json=channelFlags,proto3" json:"channel_flags,omitempty"`
	// *
	// The minimum number of blocks this node requires to be added to the expiry
	// of HTLCs. This is a security parameter determined by the node operator.
	// This value represents the required gap between the time locks of the
	// incoming and outgoing HTLC's set to this node.
	TimeLockDelta uint32 `protobuf:"varint,6,opt,name=time_lock_delta,json=timeLockDelta,proto3" json:"time_lock_delta,omitempty"`
	// *
	// The minimum HTLC value which will be accepted.
	HtlcMinimumMAtoms uint64 `protobuf:"varint,7,opt,name=htlc_minimum_m_atoms,json=htlcMinimumMAtoms,proto3" json:"htlc_minimum_m_atoms,omitempty"`
	// *
	// The base fee that must be used for incoming HTLC's to this particular
	// channel. This value will be tacked onto the required for a payment
	// independent of the size of the payment.
	BaseFee uint32 `protobuf:"varint,8,opt,name=base_fee,json=baseFee,proto3" json:"base_fee,omitempty"`
	// *
	// The fee rate that will be charged per millionth of a satoshi.
	FeeRate uint32 `protobuf:"varint,9,opt,name=fee_rate,json=feeRate,proto3" json:"fee_rate,omitempty"`
	// *
	// The maximum HTLC value which will be accepted.
	HtlcMaximumMAtoms uint64 `protobuf:"varint,11,opt,name=htlc_maximum_m_atoms,json=htlcMaximumMAtoms,proto3" json:"htlc_maximum_m_atoms,omitempty"`
	// *
	// The set of data that was appended to this message, some of which we may
	// not actually know how to iterate or parse. By holding onto this data, we
	// ensure that we're able to properly validate the set of signatures that
	// cover these new fields, and ensure we're able to make upgrades to the
	// network in a forwards compatible manner.
	ExtraOpaqueData      []byte   `protobuf:"bytes,12,opt,name=extra_opaque_data,json=extraOpaqueData,proto3" json:"extra_opaque_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelUpdate) Reset()         { *m = ChannelUpdate{} }
func (m *ChannelUpdate) String() string { return proto.CompactTextString(m) }
func (*ChannelUpdate) ProtoMessage()    {}
func (*ChannelUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_router_21c2826f7d4d1264, []int{7}
}
func (m *ChannelUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelUpdate.Unmarshal(m, b)
}
func (m *ChannelUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelUpdate.Marshal(b, m, deterministic)
}
func (dst *ChannelUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelUpdate.Merge(dst, src)
}
func (m *ChannelUpdate) XXX_Size() int {
	return xxx_messageInfo_ChannelUpdate.Size(m)
}
func (m *ChannelUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelUpdate proto.InternalMessageInfo

func (m *ChannelUpdate) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ChannelUpdate) GetChainHash() []byte {
	if m != nil {
		return m.ChainHash
	}
	return nil
}

func (m *ChannelUpdate) GetChanId() uint64 {
	if m != nil {
		return m.ChanId
	}
	return 0
}

func (m *ChannelUpdate) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ChannelUpdate) GetMessageFlags() uint32 {
	if m != nil {
		return m.MessageFlags
	}
	return 0
}

func (m *ChannelUpdate) GetChannelFlags() uint32 {
	if m != nil {
		return m.ChannelFlags
	}
	return 0
}

func (m *ChannelUpdate) GetTimeLockDelta() uint32 {
	if m != nil {
		return m.TimeLockDelta
	}
	return 0
}

func (m *ChannelUpdate) GetHtlcMinimumMAtoms() uint64 {
	if m != nil {
		return m.HtlcMinimumMAtoms
	}
	return 0
}

func (m *ChannelUpdate) GetBaseFee() uint32 {
	if m != nil {
		return m.BaseFee
	}
	return 0
}

func (m *ChannelUpdate) GetFeeRate() uint32 {
	if m != nil {
		return m.FeeRate
	}
	return 0
}

func (m *ChannelUpdate) GetHtlcMaximumMAtoms() uint64 {
	if m != nil {
		return m.HtlcMaximumMAtoms
	}
	return 0
}

func (m *ChannelUpdate) GetExtraOpaqueData() []byte {
	if m != nil {
		return m.ExtraOpaqueData
	}
	return nil
}

type ResetMissionControlRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetMissionControlRequest) Reset()         { *m = ResetMissionControlRequest{} }
func (m *ResetMissionControlRequest) String() string { return proto.CompactTextString(m) }
func (*ResetMissionControlRequest) ProtoMessage()    {}
func (*ResetMissionControlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_router_21c2826f7d4d1264, []int{8}
}
func (m *ResetMissionControlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetMissionControlRequest.Unmarshal(m, b)
}
func (m *ResetMissionControlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetMissionControlRequest.Marshal(b, m, deterministic)
}
func (dst *ResetMissionControlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetMissionControlRequest.Merge(dst, src)
}
func (m *ResetMissionControlRequest) XXX_Size() int {
	return xxx_messageInfo_ResetMissionControlRequest.Size(m)
}
func (m *ResetMissionControlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetMissionControlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetMissionControlRequest proto.InternalMessageInfo

type ResetMissionControlResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetMissionControlResponse) Reset()         { *m = ResetMissionControlResponse{} }
func (m *ResetMissionControlResponse) String() string { return proto.CompactTextString(m) }
func (*ResetMissionControlResponse) ProtoMessage()    {}
func (*ResetMissionControlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_router_21c2826f7d4d1264, []int{9}
}
func (m *ResetMissionControlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetMissionControlResponse.Unmarshal(m, b)
}
func (m *ResetMissionControlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetMissionControlResponse.Marshal(b, m, deterministic)
}
func (dst *ResetMissionControlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetMissionControlResponse.Merge(dst, src)
}
func (m *ResetMissionControlResponse) XXX_Size() int {
	return xxx_messageInfo_ResetMissionControlResponse.Size(m)
}
func (m *ResetMissionControlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetMissionControlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetMissionControlResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PaymentRequest)(nil), "routerrpc.PaymentRequest")
	proto.RegisterType((*PaymentResponse)(nil), "routerrpc.PaymentResponse")
	proto.RegisterType((*RouteFeeRequest)(nil), "routerrpc.RouteFeeRequest")
	proto.RegisterType((*RouteFeeResponse)(nil), "routerrpc.RouteFeeResponse")
	proto.RegisterType((*SendToRouteRequest)(nil), "routerrpc.SendToRouteRequest")
	proto.RegisterType((*SendToRouteResponse)(nil), "routerrpc.SendToRouteResponse")
	proto.RegisterType((*Failure)(nil), "routerrpc.Failure")
	proto.RegisterType((*ChannelUpdate)(nil), "routerrpc.ChannelUpdate")
	proto.RegisterType((*ResetMissionControlRequest)(nil), "routerrpc.ResetMissionControlRequest")
	proto.RegisterType((*ResetMissionControlResponse)(nil), "routerrpc.ResetMissionControlResponse")
	proto.RegisterEnum("routerrpc.Failure_FailureCode", Failure_FailureCode_name, Failure_FailureCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RouterClient is the client API for Router service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouterClient interface {
	// *
	// SendPayment attempts to route a payment described by the passed
	// PaymentRequest to the final destination. If we are unable to route the
	// payment, or cannot find a route that satisfies the constraints in the
	// PaymentRequest, then an error will be returned. Otherwise, the payment
	// pre-image, along with the final route will be returned.
	SendPayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
	// *
	// EstimateRouteFee allows callers to obtain a lower bound w.r.t how much it
	// may cost to send an HTLC to the target end destination.
	EstimateRouteFee(ctx context.Context, in *RouteFeeRequest, opts ...grpc.CallOption) (*RouteFeeResponse, error)
	// *
	// SendToRoute attempts to make a payment via the specified route. This method
	// differs from SendPayment in that it allows users to specify a full route
	// manually. This can be used for things like rebalancing, and atomic swaps.
	SendToRoute(ctx context.Context, in *SendToRouteRequest, opts ...grpc.CallOption) (*SendToRouteResponse, error)
	// *
	// ResetMissionControl clears all mission control state and starts with a clean
	// slate.
	ResetMissionControl(ctx context.Context, in *ResetMissionControlRequest, opts ...grpc.CallOption) (*ResetMissionControlResponse, error)
}

type routerClient struct {
	cc *grpc.ClientConn
}

func NewRouterClient(cc *grpc.ClientConn) RouterClient {
	return &routerClient{cc}
}

func (c *routerClient) SendPayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, "/routerrpc.Router/SendPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) EstimateRouteFee(ctx context.Context, in *RouteFeeRequest, opts ...grpc.CallOption) (*RouteFeeResponse, error) {
	out := new(RouteFeeResponse)
	err := c.cc.Invoke(ctx, "/routerrpc.Router/EstimateRouteFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) SendToRoute(ctx context.Context, in *SendToRouteRequest, opts ...grpc.CallOption) (*SendToRouteResponse, error) {
	out := new(SendToRouteResponse)
	err := c.cc.Invoke(ctx, "/routerrpc.Router/SendToRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) ResetMissionControl(ctx context.Context, in *ResetMissionControlRequest, opts ...grpc.CallOption) (*ResetMissionControlResponse, error) {
	out := new(ResetMissionControlResponse)
	err := c.cc.Invoke(ctx, "/routerrpc.Router/ResetMissionControl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterServer is the server API for Router service.
type RouterServer interface {
	// *
	// SendPayment attempts to route a payment described by the passed
	// PaymentRequest to the final destination. If we are unable to route the
	// payment, or cannot find a route that satisfies the constraints in the
	// PaymentRequest, then an error will be returned. Otherwise, the payment
	// pre-image, along with the final route will be returned.
	SendPayment(context.Context, *PaymentRequest) (*PaymentResponse, error)
	// *
	// EstimateRouteFee allows callers to obtain a lower bound w.r.t how much it
	// may cost to send an HTLC to the target end destination.
	EstimateRouteFee(context.Context, *RouteFeeRequest) (*RouteFeeResponse, error)
	// *
	// SendToRoute attempts to make a payment via the specified route. This method
	// differs from SendPayment in that it allows users to specify a full route
	// manually. This can be used for things like rebalancing, and atomic swaps.
	SendToRoute(context.Context, *SendToRouteRequest) (*SendToRouteResponse, error)
	// *
	// ResetMissionControl clears all mission control state and starts with a clean
	// slate.
	ResetMissionControl(context.Context, *ResetMissionControlRequest) (*ResetMissionControlResponse, error)
}

func RegisterRouterServer(s *grpc.Server, srv RouterServer) {
	s.RegisterService(&_Router_serviceDesc, srv)
}

func _Router_SendPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).SendPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routerrpc.Router/SendPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).SendPayment(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_EstimateRouteFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).EstimateRouteFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routerrpc.Router/EstimateRouteFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).EstimateRouteFee(ctx, req.(*RouteFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_SendToRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).SendToRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routerrpc.Router/SendToRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).SendToRoute(ctx, req.(*SendToRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_ResetMissionControl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetMissionControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).ResetMissionControl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routerrpc.Router/ResetMissionControl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).ResetMissionControl(ctx, req.(*ResetMissionControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Router_serviceDesc = grpc.ServiceDesc{
	ServiceName: "routerrpc.Router",
	HandlerType: (*RouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPayment",
			Handler:    _Router_SendPayment_Handler,
		},
		{
			MethodName: "EstimateRouteFee",
			Handler:    _Router_EstimateRouteFee_Handler,
		},
		{
			MethodName: "SendToRoute",
			Handler:    _Router_SendToRoute_Handler,
		},
		{
			MethodName: "ResetMissionControl",
			Handler:    _Router_ResetMissionControl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "routerrpc/router.proto",
}

func init() { proto.RegisterFile("routerrpc/router.proto", fileDescriptor_router_21c2826f7d4d1264) }

var fileDescriptor_router_21c2826f7d4d1264 = []byte{
	// 1267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x56, 0xdd, 0x72, 0xda, 0x46,
	0x14, 0x2e, 0xf1, 0x0f, 0x70, 0x00, 0x23, 0xaf, 0xed, 0x04, 0xe3, 0x38, 0x71, 0x68, 0x9b, 0x7a,
	0x32, 0x19, 0x7b, 0x86, 0x4e, 0x72, 0xdb, 0x91, 0x61, 0xa9, 0x35, 0x41, 0x12, 0x5d, 0xc0, 0x89,
	0xdb, 0x8b, 0x9d, 0xb5, 0xb4, 0x06, 0x35, 0xe8, 0xc7, 0x92, 0xe8, 0xd8, 0xcf, 0xd0, 0x27, 0xea,
	0x23, 0xf4, 0xaa, 0xd7, 0x7d, 0x9b, 0xce, 0xee, 0x4a, 0x18, 0x1c, 0x67, 0x7a, 0x65, 0xef, 0xf7,
	0x7d, 0x3a, 0x67, 0xcf, 0xd9, 0xf3, 0x03, 0x3c, 0x8d, 0xc3, 0x79, 0xca, 0xe3, 0x38, 0x72, 0x4e,
	0xd5, 0x7f, 0x27, 0x51, 0x1c, 0xa6, 0x21, 0x2a, 0x2f, 0xf0, 0x66, 0x39, 0x8e, 0x1c, 0x85, 0xb6,
	0xfe, 0x2e, 0xc0, 0xd6, 0x80, 0xdd, 0xf9, 0x3c, 0x48, 0x09, 0xbf, 0x99, 0xf3, 0x24, 0x45, 0xcf,
	0xa0, 0x18, 0xb1, 0x3b, 0x1a, 0xf3, 0x9b, 0x46, 0xe1, 0xa8, 0x70, 0x5c, 0x26, 0x9b, 0x11, 0xbb,
	0x23, 0xfc, 0x06, 0xbd, 0x86, 0xfa, 0x35, 0xe7, 0x74, 0xe6, 0xf9, 0x5e, 0x4a, 0x59, 0x1a, 0xfa,
	0x49, 0xe3, 0xc9, 0x51, 0xe1, 0x78, 0x8d, 0xd4, 0xae, 0x39, 0xef, 0x0b, 0x54, 0x17, 0x20, 0x3a,
	0x04, 0x70, 0x66, 0xe9, 0x1f, 0x4a, 0xd8, 0x58, 0x3b, 0x2a, 0x1c, 0x6f, 0x90, 0xb2, 0x40, 0xa4,
	0x06, 0xfd, 0x00, 0xf5, 0xd4, 0xf3, 0x79, 0x38, 0x4f, 0x69, 0xc2, 0x9d, 0x30, 0x70, 0x93, 0xc6,
	0xba, 0xd4, 0x6c, 0x65, 0xf0, 0x50, 0xa1, 0xe8, 0x04, 0x76, 0xc2, 0x79, 0x3a, 0x09, 0xbd, 0x60,
	0x42, 0x9d, 0x29, 0x0b, 0x02, 0x3e, 0xa3, 0x9e, 0xdb, 0xd8, 0x90, 0x3e, 0xb7, 0x73, 0xaa, 0xa3,
	0x18, 0xc3, 0x6d, 0xfd, 0x0e, 0xf5, 0x45, 0x28, 0x49, 0x14, 0x06, 0x09, 0x47, 0xfb, 0x50, 0x12,
	0xb1, 0x4c, 0x59, 0x32, 0x95, 0xc1, 0x54, 0x89, 0x88, 0xed, 0x9c, 0x25, 0x53, 0x74, 0x00, 0xe5,
	0x28, 0xe6, 0xd4, 0xf3, 0xd9, 0x84, 0xcb, 0x38, 0xaa, 0xa4, 0x14, 0xc5, 0xdc, 0x10, 0x67, 0xf4,
	0x12, 0x2a, 0x91, 0x32, 0x45, 0x79, 0x1c, 0xcb, 0x18, 0xca, 0x04, 0x32, 0x08, 0xc7, 0x71, 0xeb,
	0x0c, 0xea, 0x44, 0xe4, 0xb3, 0xc7, 0x79, 0x9e, 0x37, 0x04, 0xeb, 0x2e, 0x4f, 0xd2, 0xcc, 0x8f,
	0xfc, 0x5f, 0x38, 0x61, 0xfe, 0x6a, 0xb2, 0x4a, 0xcc, 0x57, 0x79, 0x6a, 0x4d, 0x41, 0xbb, 0xb7,
	0x91, 0x5d, 0xf8, 0x2d, 0x20, 0xf1, 0x4e, 0x22, 0x64, 0x91, 0x6b, 0x5f, 0x7d, 0x59, 0x90, 0x5f,
	0x6a, 0x19, 0xd3, 0xe3, 0xdc, 0x94, 0xb8, 0x78, 0x11, 0x91, 0x33, 0x3a, 0x0b, 0x9d, 0xcf, 0xd4,
	0xe5, 0x33, 0x76, 0x97, 0xbf, 0x88, 0x80, 0xfb, 0xa1, 0xf3, 0xb9, 0x2b, 0xc0, 0xd6, 0x6f, 0x80,
	0x86, 0x3c, 0x70, 0x47, 0xa1, 0xf4, 0x97, 0x5f, 0xf8, 0x15, 0x54, 0xf3, 0x20, 0x97, 0x12, 0x94,
	0x07, 0x2e, 0x93, 0xd4, 0x82, 0x0d, 0x59, 0x36, 0xd2, 0x6c, 0xa5, 0x5d, 0x3d, 0x99, 0x05, 0xa2,
	0x76, 0x94, 0x19, 0x45, 0xb5, 0x28, 0xec, 0xac, 0x18, 0xcf, 0x22, 0x69, 0x82, 0x48, 0xa7, 0x4a,
	0x6f, 0x61, 0x91, 0x5e, 0x79, 0x46, 0x6f, 0xa1, 0x78, 0xcd, 0xbc, 0xd9, 0x3c, 0xce, 0x0d, 0xa3,
	0x93, 0x45, 0x75, 0x9e, 0xf4, 0x14, 0x43, 0x72, 0x49, 0xeb, 0xcf, 0x22, 0x14, 0x33, 0x10, 0xb5,
	0x61, 0xdd, 0x09, 0x5d, 0x65, 0x71, 0xab, 0xfd, 0xe2, 0xcb, 0xcf, 0xf2, 0xbf, 0x9d, 0xd0, 0xe5,
	0x44, 0x6a, 0x51, 0x1b, 0xf6, 0x32, 0x53, 0x34, 0x09, 0xe7, 0xb1, 0xc3, 0x69, 0x34, 0xbf, 0xfa,
	0xcc, 0xef, 0xb2, 0x57, 0xdf, 0xc9, 0xc8, 0xa1, 0xe4, 0x06, 0x92, 0x42, 0x3f, 0xc1, 0x56, 0x5e,
	0x72, 0xf3, 0xc8, 0x65, 0x29, 0x97, 0x35, 0x50, 0x69, 0x37, 0x96, 0x3c, 0x66, 0x95, 0x37, 0x96,
	0x3c, 0xa9, 0x39, 0xcb, 0x47, 0x74, 0x04, 0xd5, 0x69, 0x3a, 0x73, 0xa8, 0x9f, 0x3d, 0xbe, 0x28,
	0xf1, 0x75, 0x02, 0x02, 0x33, 0x55, 0x9b, 0xb4, 0xa0, 0x16, 0x06, 0x5e, 0x18, 0xd0, 0x64, 0xca,
	0x68, 0xfb, 0xdd, 0x7b, 0x59, 0xd8, 0x55, 0x52, 0x91, 0xe0, 0x70, 0xca, 0xda, 0xef, 0xde, 0x8b,
	0x3a, 0x94, 0xad, 0xc4, 0x6f, 0x23, 0x2f, 0xbe, 0x6b, 0x6c, 0x1e, 0x15, 0x8e, 0x6b, 0x44, 0x76,
	0x17, 0x96, 0x08, 0xda, 0x85, 0x8d, 0xeb, 0x19, 0x9b, 0x24, 0x8d, 0xa2, 0xa4, 0xd4, 0xa1, 0xf5,
	0xef, 0x3a, 0x54, 0x96, 0xf2, 0x80, 0xaa, 0x50, 0x22, 0x78, 0x88, 0xc9, 0x05, 0xee, 0x6a, 0xdf,
	0xa0, 0x06, 0xec, 0x8e, 0xad, 0x0f, 0x96, 0xfd, 0xd1, 0xa2, 0x03, 0xfd, 0xd2, 0xc4, 0xd6, 0x88,
	0x9e, 0xeb, 0xc3, 0x73, 0xad, 0x80, 0x9e, 0x43, 0xc3, 0xb0, 0x3a, 0x36, 0x21, 0xb8, 0x33, 0x5a,
	0x70, 0xba, 0x69, 0x8f, 0xad, 0x91, 0xf6, 0x04, 0xbd, 0x84, 0x83, 0x9e, 0x61, 0xe9, 0x7d, 0x7a,
	0xaf, 0xe9, 0xf4, 0x47, 0x17, 0x14, 0x7f, 0x1a, 0x18, 0xe4, 0x52, 0x5b, 0x7b, 0x4c, 0x70, 0x3e,
	0xea, 0x77, 0x72, 0x0b, 0xeb, 0x68, 0x1f, 0xf6, 0x94, 0x40, 0x7d, 0x42, 0x47, 0xb6, 0x4d, 0x87,
	0xb6, 0x6d, 0x69, 0x1b, 0x68, 0x1b, 0x6a, 0x86, 0x75, 0xa1, 0xf7, 0x8d, 0x2e, 0x25, 0x58, 0xef,
	0x9b, 0xda, 0x26, 0xda, 0x81, 0xfa, 0x43, 0x5d, 0x51, 0x98, 0xc8, 0x75, 0xb6, 0x65, 0xd8, 0x16,
	0xbd, 0xc0, 0x64, 0x68, 0xd8, 0x96, 0x56, 0x42, 0x4f, 0x01, 0xad, 0x52, 0xe7, 0xa6, 0xde, 0xd1,
	0xca, 0x68, 0x0f, 0xb6, 0x57, 0xf1, 0x0f, 0xf8, 0x52, 0x03, 0x91, 0x06, 0x75, 0x31, 0x7a, 0x86,
	0xfb, 0xf6, 0x47, 0x6a, 0x1a, 0x96, 0x61, 0x8e, 0x4d, 0xad, 0x82, 0x76, 0x41, 0xeb, 0x61, 0x4c,
	0x0d, 0x6b, 0x38, 0xee, 0xf5, 0x8c, 0x8e, 0x81, 0xad, 0x91, 0x56, 0x55, 0x9e, 0x1f, 0x0b, 0xbc,
	0x26, 0x3e, 0xe8, 0x9c, 0xeb, 0x96, 0x85, 0xfb, 0xb4, 0x6b, 0x0c, 0xf5, 0xb3, 0x3e, 0xee, 0x6a,
	0x5b, 0xe8, 0x10, 0xf6, 0x47, 0xd8, 0x1c, 0xd8, 0x44, 0x27, 0x97, 0x34, 0xe7, 0x7b, 0xba, 0xd1,
	0x1f, 0x13, 0xac, 0xd5, 0xd1, 0x2b, 0x38, 0x24, 0xf8, 0x97, 0xb1, 0x41, 0x70, 0x97, 0x5a, 0x76,
	0x17, 0xd3, 0x1e, 0xd6, 0x47, 0x63, 0x82, 0xa9, 0x69, 0x0c, 0x87, 0x86, 0xf5, 0xb3, 0xa6, 0xa1,
	0xef, 0xe0, 0x68, 0x21, 0x59, 0x18, 0x78, 0xa0, 0xda, 0x16, 0xf1, 0xe5, 0xef, 0x69, 0xe1, 0x4f,
	0x23, 0x3a, 0xc0, 0x98, 0x68, 0x08, 0x35, 0xe1, 0xe9, 0xbd, 0x7b, 0xe5, 0x20, 0xf3, 0xbd, 0x23,
	0xb8, 0x01, 0x26, 0xa6, 0x6e, 0x89, 0x07, 0x5e, 0xe1, 0x76, 0xc5, 0xb5, 0xef, 0xb9, 0x87, 0xd7,
	0xde, 0x6b, 0xfd, 0xb5, 0x06, 0xb5, 0x95, 0xca, 0x47, 0xcf, 0xa1, 0x9c, 0x78, 0x93, 0x80, 0xa5,
	0xa2, 0x9f, 0x55, 0xab, 0xdf, 0x03, 0x72, 0x1b, 0x4c, 0x99, 0x17, 0xa8, 0x19, 0xa3, 0x5a, 0xae,
	0x2c, 0x11, 0x39, 0x61, 0x9e, 0x41, 0x51, 0x34, 0x8e, 0x18, 0xec, 0x6b, 0xb2, 0x45, 0x36, 0xc5,
	0xd1, 0x70, 0x85, 0x55, 0x31, 0xc4, 0x92, 0x94, 0xf9, 0x91, 0xec, 0x9e, 0x1a, 0xb9, 0x07, 0xd0,
	0xb7, 0x50, 0xf3, 0x79, 0x92, 0xb0, 0x09, 0xa7, 0xaa, 0xfe, 0x41, 0x2a, 0xaa, 0x19, 0xd8, 0x13,
	0x98, 0x10, 0xe5, 0x4d, 0xac, 0x44, 0x1b, 0x4a, 0x94, 0x81, 0x4a, 0xf4, 0x70, 0x86, 0xa6, 0x2c,
	0x6b, 0xb3, 0xe5, 0x19, 0x9a, 0x32, 0x74, 0x0a, 0xbb, 0xaa, 0xa1, 0xbd, 0xc0, 0xf3, 0xe7, 0xfe,
	0xa2, 0xb1, 0x8b, 0xf2, 0xd6, 0xdb, 0xb2, 0xb1, 0x15, 0x95, 0xf5, 0xf7, 0x3e, 0x94, 0xae, 0x58,
	0xc2, 0xc5, 0x1c, 0x6f, 0x94, 0xa4, 0xc5, 0xa2, 0x38, 0xf7, 0xb8, 0x5c, 0x4b, 0x62, 0xba, 0xc7,
	0x62, 0xae, 0x94, 0x15, 0x75, 0xcd, 0x39, 0x11, 0xc9, 0x5c, 0xb8, 0x61, 0xb7, 0x2b, 0x6e, 0x2a,
	0x4b, 0x6e, 0x14, 0x95, 0xb9, 0x79, 0x03, 0xdb, 0xfc, 0x36, 0x8d, 0x19, 0x0d, 0x23, 0x76, 0x33,
	0xe7, 0xd4, 0x65, 0x29, 0x6b, 0x54, 0x65, 0x9a, 0xeb, 0x92, 0xb0, 0x25, 0xde, 0x65, 0x29, 0x6b,
	0x3d, 0x87, 0x26, 0xe1, 0x09, 0x4f, 0x4d, 0x2f, 0x49, 0xbc, 0x30, 0xe8, 0x84, 0x41, 0x1a, 0x87,
	0xb3, 0x6c, 0x1f, 0xb4, 0x0e, 0xe1, 0xe0, 0x51, 0x56, 0x0d, 0xf4, 0xf6, 0x3f, 0x4f, 0x60, 0x53,
	0x8e, 0xf8, 0x18, 0x75, 0xa1, 0x22, 0x46, 0x7e, 0xb6, 0x6d, 0xd1, 0xfe, 0xd2, 0x50, 0x5c, 0xfd,
	0x31, 0xd1, 0x6c, 0x3e, 0x46, 0x65, 0x1b, 0xe2, 0x03, 0x68, 0x38, 0x49, 0x3d, 0x5f, 0x4c, 0xcf,
	0x6c, 0x0f, 0xa2, 0x65, 0xfd, 0x83, 0x05, 0xdb, 0x3c, 0x78, 0x94, 0xcb, 0x8c, 0xf5, 0xd5, 0x95,
	0xb2, 0x2d, 0x84, 0x0e, 0x97, 0xb4, 0x5f, 0xae, 0xbe, 0xe6, 0x8b, 0xaf, 0xd1, 0x99, 0x35, 0x17,
	0x76, 0x1e, 0x49, 0x05, 0xfa, 0x7e, 0xf9, 0x06, 0x5f, 0x4d, 0x64, 0xf3, 0xf5, 0xff, 0xc9, 0x94,
	0x97, 0xb3, 0x37, 0xbf, 0x1e, 0x4f, 0xbc, 0x74, 0x3a, 0xbf, 0x3a, 0x71, 0x42, 0xff, 0xd4, 0xe5,
	0x4e, 0xcc, 0xdd, 0x53, 0xd7, 0x89, 0x67, 0x81, 0x7b, 0x2a, 0x17, 0xed, 0xe9, 0xc2, 0xce, 0xd5,
	0xa6, 0xfc, 0xbd, 0xf6, 0xe3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xf6, 0x96, 0xe5, 0xdf,
	0x09, 0x00, 0x00,
}
